// Runbook spike (decision 0104, plan docs/plans/runbook-spike.md): an on-demand skill generated from knowledge, never
// edited. Built around a guardrail (its norm, the steps of the procedures that operationalize it, the facts it is
// grounded in) or around a procedure (its steps, what it `uses`, the norms it operationalizes).
import { readFileSync, readdirSync, existsSync } from 'node:fs';
import path from 'node:path';
import { parseFrontmatter } from './frontmatter.mjs';
import { ARTIFACT_TYPES } from './artifacts.mjs';

export const runbookPath = (guardrailId) => `docs/runbooks/${guardrailId}/SKILL.md`;

const list = (v) => (v == null ? [] : Array.isArray(v) ? v : [v]).map(String).filter(Boolean);

// Every artifact under docs/<type>/ and docs/<type>/archive/, keyed by id.
function load(root) {
  const byId = new Map();
  for (const type of ARTIFACT_TYPES) {
    for (const dir of [path.join('docs', type), path.join('docs', type, 'archive')]) {
      if (!existsSync(path.join(root, dir))) continue;
      for (const name of readdirSync(path.join(root, dir)).sort()) {
        if (!name.endsWith('.md') || name === 'INDEX.md') continue;
        const { data, body } = parseFrontmatter(readFileSync(path.join(root, dir, name), 'utf8'));
        byId.set(name.slice(0, -3), { id: name.slice(0, -3), type, data, body });
      }
    }
  }
  return byId;
}

// The body without its leading `## Guardrail` / `## Procedure` heading.
const content = (body) => body.trim().replace(/^## (?:Guardrail|Procedure)\s*\n/, '').trim();

// The text under `heading` (any level) up to the next heading of the same or a higher level, without the heading line.
export function sectionOf(body, heading) {
  const lines = body.split('\n');
  const level = (l) => /^(#{1,6})\s/.exec(l)?.[1].length ?? 0;
  const start = lines.findIndex((l) => level(l) && l.replace(/^#{1,6}\s+/, '').trim() === heading);
  if (start < 0) return null;
  const depth = level(lines[start]);
  let end = lines.length;
  for (let i = start + 1; i < lines.length; i++) {
    if (level(lines[i]) && level(lines[i]) <= depth) {
      end = i;
      break;
    }
  }
  return lines.slice(start + 1, end).join('\n').trim();
}

// The runbook of a procedure: its steps, each artifact it `uses` (`id`, or `id#Heading` for one section), then the
// norms of the guardrails it operationalizes.
function buildProcedureRunbook(byId, procedure) {
  const id = procedure.id;
  const used = list(procedure.data.uses).map((ref) => {
    const [artifactId, ...rest] = ref.split('#');
    const heading = rest.join('#').trim();
    const a = byId.get(artifactId.trim());
    if (!a) throw new Error(`runbook: "${id}" uses "${artifactId.trim()}", which does not exist`);
    if (!heading) return { id: a.id, title: a.data.title, text: content(a.body) };
    const text = sectionOf(a.body, heading);
    if (text == null) throw new Error(`runbook: "${id}" uses "${a.id}#${heading}", but ${a.id} has no heading "${heading}"`);
    return { id: a.id, title: `${a.data.title}: ${heading}`, text };
  });
  const norms = list(procedure.data.operationalizes).map((gid) => {
    const g = byId.get(gid);
    if (!g || g.type !== 'guardrails') throw new Error(`runbook: "${id}" operationalizes "${gid}", which is not a guardrail`);
    return g;
  });
  const sources = [id, ...used.map((u) => u.id), ...norms.map((g) => g.id)];
  const lines = [
    '---',
    `name: ${id}`,
    `description: Use when the task involves: ${procedure.data.title}.`,
    '---',
    '',
    `<!-- Generated by go-getter runbook from ${[...new Set(sources)].join(', ')}; do not edit. -->`,
    '',
    '## Steps',
    '',
    content(procedure.body),
    '',
  ];
  if (used.length) {
    lines.push('## Uses', '');
    for (const u of used) lines.push(`### ${u.title}`, '', u.text, '');
  }
  if (norms.length) {
    lines.push('## Norms', '');
    for (const g of norms) lines.push(`### ${g.data.title}`, '', content(g.body), '');
  }
  return `${lines.join('\n').replace(/\n+$/, '')}\n`;
}

export function buildRunbook(root, guardrailId) {
  const byId = load(root);
  const procedure = byId.get(guardrailId);
  if (procedure && procedure.type === 'skills') return buildProcedureRunbook(byId, procedure);
  const guardrail = byId.get(guardrailId);
  if (!guardrail || guardrail.type !== 'guardrails') throw new Error(`runbook: no guardrail or procedure "${guardrailId}"`);
  const procedures = [...byId.values()].filter((a) => a.type === 'skills' && list(a.data.operationalizes).includes(guardrailId));
  if (!procedures.length) throw new Error(`runbook: guardrail "${guardrailId}" has no procedure that operationalizes it`);
  const grounded = list(guardrail.data['grounded-in']).map((id) => {
    const a = byId.get(id);
    if (!a) throw new Error(`runbook: "${guardrailId}" is grounded in "${id}", which does not exist`);
    return a;
  });
  const facts = grounded.filter((a) => a.type === 'facts');
  const named = grounded.filter((a) => a.type !== 'facts');
  const sources = [guardrail, ...procedures, ...facts].map((a) => a.id);
  const lines = [
    '---',
    `name: ${guardrailId}`,
    `description: Use when the task involves: ${guardrail.data.title}.`,
    '---',
    '',
    `<!-- Generated by go-getter runbook from ${sources.join(', ')}; do not edit. -->`,
    '',
    '## Norm',
    '',
    content(guardrail.body),
    '',
    '## Steps',
    '',
  ];
  for (const p of procedures) lines.push(...(procedures.length > 1 ? [`### ${p.data.title}`, ''] : []), content(p.body), '');
  if (facts.length) {
    lines.push('## Facts', '');
    for (const f of facts) lines.push(`### ${f.data.title}`, '', content(f.body), '');
  }
  if (named.length) lines.push('## Grounded in', '', ...named.map((a) => `- ${a.id}`), '');
  return `${lines.join('\n').replace(/\n+$/, '')}\n`;
}

// { ok, message }: the committed runbook equals a fresh build.
export function checkRunbook(root, guardrailId) {
  const file = path.join(root, runbookPath(guardrailId));
  if (!existsSync(file)) return { ok: false, message: `${runbookPath(guardrailId)} does not exist; run go-getter runbook build ${guardrailId}` };
  return readFileSync(file, 'utf8') === buildRunbook(root, guardrailId)
    ? { ok: true }
    : { ok: false, message: `${runbookPath(guardrailId)} is out of date; run go-getter runbook build ${guardrailId}` };
}
