// Agent definitions (plan 5.2, decision 0014): the roster decision's `go-getter.roles` compiled to each host's native agent format.
// Role data lives in adopted orchestration decisions (decision 0007); this module only renders it.
import { existsSync, readFileSync, readdirSync } from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';
import { readArtifacts } from './artifacts.mjs';
import { loadCapabilities } from './capabilities.mjs';

const PACKAGE_ROOT = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..', '..');
export const AGENT_MARKER = 'Generated by go-getter apply';

// Read-only roles get these on hosts with tool lists (names are host-native; unconfirmed ones are noted in fact 0015).
const READ_ONLY_TOOLS = {
  'claude-code': 'Read, Grep, Glob',
  'gemini-cli': ['read_file', 'list_directory', 'glob', 'grep_search'],
  copilot: ['read', 'search'],
};

// The adopted orchestration data: roles with access overrides and the shared contract text.
export function readRoster(project) {
  const decisions = readArtifacts(project, ['decisions']).filter((d) => d.data.status === 'active' && String(d.data['go-getter']?.['generated-by'] ?? '').startsWith('orchestration@'));
  const roster = decisions.find((d) => d.data['go-getter'].roles);
  if (!roster) return null;
  const merged = (key) => Object.assign({}, ...decisions.map((d) => d.data['go-getter'][key] ?? {}));
  const text = (key) => decisions.map((d) => d.data['go-getter'][key]).find(Boolean) ?? null;
  const access = merged('role-access');
  const notes = merged('role-notes');
  return {
    decision: roster.id,
    roles: roster.data['go-getter'].roles.map((r) => ({ ...r, access: access[r.id] ?? r.access, note: notes[r.id] ?? null })),
    handoff: text('handoff'),
    escalation: text('escalation'),
  };
}

// Instruction text shared by every host's format.
export function roleBody(roster, role) {
  const lines = [role.instructions];
  if (role.note) lines.push(role.note);
  if (roster.handoff) lines.push(`Handoff: ${roster.handoff}`);
  if (roster.escalation) lines.push(`Escalation: ${roster.escalation}`);
  return lines.join('\n\n');
}

const tag = (roster, role) => `${AGENT_MARKER} from ${roster.decision}; do not edit. role=${role.id} task-class=${role['task-class']}`;
const yamlList = (items) => `[${items.map((i) => JSON.stringify(i)).join(', ')}]`;

// One renderer per host: (roster, role) -> file content.
const RENDER = {
  'claude-code': (r, role) => md({ name: role.id, description: role.description, ...(role.access === 'read-only' ? { tools: READ_ONLY_TOOLS['claude-code'] } : {}) }, r, role),
  'kilo-opencode': (r, role) => {
    const head = { description: role.description, mode: 'subagent' };
    const permission = role.access === 'read-only' ? '\npermission:\n  edit: deny\n  bash: deny' : '';
    return md(head, r, role, permission);
  },
  cursor: (r, role) => md({ name: role.id, description: role.description, ...(role.access === 'read-only' ? { readonly: true } : {}) }, r, role),
  'gemini-cli': (r, role) => md({ name: role.id, description: role.description, kind: 'local' }, r, role, role.access === 'read-only' ? `\ntools: ${yamlList(READ_ONLY_TOOLS['gemini-cli'])}` : ''),
  copilot: (r, role) => md({ name: role.id, description: role.description }, r, role, role.access === 'read-only' ? `\ntools: ${yamlList(READ_ONLY_TOOLS.copilot)}` : ''),
  codex: (r, role) =>
    [
      `# ${tag(r, role)}`,
      `name = ${JSON.stringify(role.id)}`,
      `description = ${JSON.stringify(role.description)}`,
      `sandbox_mode = ${JSON.stringify(role.access === 'read-only' ? 'read-only' : 'workspace-write')}`,
      `developer_instructions = ${JSON.stringify(roleBody(r, role))}`,
      '',
    ].join('\n'),
};

function md(head, roster, role, extraYaml = '') {
  const lines = Object.entries(head).map(([k, v]) => `${k}: ${typeof v === 'string' && !/^[A-Za-z][A-Za-z0-9 ,-]*$/.test(v) ? JSON.stringify(v) : v}`);
  return `---\n${lines.join('\n')}${extraYaml}\n---\n\n${roleBody(roster, role)}\n\n<!-- ${tag(roster, role)} -->\n`;
}

// {path: {content}} for every role on every host that has native agents.
export function agentOutputs(project, hosts, caps = loadCapabilities(PACKAGE_ROOT)) {
  const roster = readRoster(project);
  const out = {};
  if (!roster) return out;
  for (const host of hosts) {
    const agents = caps[host]?.agents;
    if (!agents || !RENDER[host]) continue;
    for (const role of roster.roles) out[`${agents.dir}/${role.id}${agents.extension}`] = { content: RENDER[host](roster, role) };
  }
  return out;
}

// Generated agent files in `hosts`' agent dirs that the current roster no longer produces.
export function staleAgentFiles(project, hosts, planned, caps = loadCapabilities(PACKAGE_ROOT)) {
  const stale = [];
  for (const host of hosts) {
    const agents = caps[host]?.agents;
    const dir = agents && path.join(project, agents.dir);
    if (!dir || !existsSync(dir)) continue;
    for (const name of readdirSync(dir).sort()) {
      const rel = `${agents.dir}/${name}`;
      if (name.endsWith(agents.extension) && !(rel in planned) && readFileSync(path.join(dir, name), 'utf8').includes(AGENT_MARKER)) stale.push(rel);
    }
  }
  return stale;
}
