// `go-getter apply` (plan 4.4): materializes guardrail enforcement into project-local files (decision 0021, output kind B).
// Outputs are planned first ({path: {content, mode?} | {symlink}}) so the same plan drives writing and drift checking.
import { existsSync, readFileSync, lstatSync, readlinkSync, mkdirSync, writeFileSync, symlinkSync, chmodSync, readdirSync, statSync, rmSync } from 'node:fs';
import { fileURLToPath } from 'node:url';
import { execFileSync } from 'node:child_process';
import path from 'node:path';
import { collectEnforcement } from './enforce.mjs';
import { detect } from './detect.mjs';
import { HOSTS } from './capabilities.mjs';
import { agentOutputs, staleAgentFiles } from './agents.mjs';
import { packageCapabilities, promptLoggingTargets, setPath } from './governance.mjs';
import { loadPolicy } from './routing/policy.mjs';

export const RUNNER = '.go-getter/bin/go-getter';
const MARK_START = '<!-- go-getter:start -->';
const MARK_END = '<!-- go-getter:end -->';
const HOOK_TAG = `${RUNNER} hook`;
const NODE_FLOOR = 22;

const runnerScript = `#!/bin/sh
# Generated by go-getter apply; do not edit. Runs the go-getter CLI when Node >= ${NODE_FLOOR} is available,
# otherwise warns and exits 0 so enforcement degrades to advisory (decision 0019).
FLOOR=${NODE_FLOOR}
if ! command -v node >/dev/null 2>&1; then
  echo "go-getter: enforcement unavailable: Node >= $FLOOR not found" >&2
  exit 0
fi
MAJOR=$(node -p 'process.versions.node.split(".")[0]')
if [ "$MAJOR" -lt "$FLOOR" ]; then
  echo "go-getter: enforcement unavailable: Node $MAJOR < $FLOOR" >&2
  exit 0
fi
ROOT=$(git rev-parse --show-toplevel 2>/dev/null || pwd)
if [ -f "$ROOT/compiler/bin/go-getter.mjs" ] && grep -q '"name": "go-getter"' "$ROOT/package.json" 2>/dev/null; then
  exec node "$ROOT/compiler/bin/go-getter.mjs" "$@"
fi
exec npx --yes github:vivantel/go-getter "$@"
`;

const prePush = `#!/bin/sh
# Generated by go-getter apply; do not edit. Tier-3 guardrail checks before every push (decision 0009).
exec "$(git rev-parse --show-toplevel)/${RUNNER}" check --stage pre-push
`;

const ciWorkflow = `# Generated by go-getter apply; do not edit. Tier-3 guardrail checks (decision 0009).
name: go-getter checks

on:
  pull_request:
  push:
    branches: [main]

permissions:
  contents: read

jobs:
  go-getter-checks:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          fetch-depth: 0
      - uses: actions/setup-node@820762786026740c76f36085b0efc47a31fe5020 # v7.0.0
        with:
          node-version: ${NODE_FLOOR}
      - run: sh ${RUNNER} check --stage ci
`;

function guardrailSection(entries) {
  const byGuardrail = new Map();
  for (const e of entries) {
    const g = byGuardrail.get(e.guardrail) ?? { title: e.title, tiers: new Set() };
    g.tiers.add(e.tier);
    byGuardrail.set(e.guardrail, g);
  }
  const groups = { 3: [], 2: [], 1: [] };
  for (const [id, g] of [...byGuardrail].sort()) groups[Math.max(...g.tiers)].push(`- ${g.title} (\`${id}\`)`);
  const lines = [MARK_START, '## Guardrails', '', 'Generated by `go-getter apply` from `docs/guardrails/`; do not edit this section.', ''];
  if (groups[3].length) lines.push('Checked by git hooks and CI:', '', ...groups[3], '');
  if (groups[2].length) lines.push('Blocked by host hooks where the host supports it:', '', ...groups[2], '');
  if (groups[1].length) lines.push('Advisory:', '', ...groups[1], '');
  lines.push(MARK_END);
  return lines.join('\n');
}

export function withSection(existing, section) {
  if (existing.includes(MARK_START) && existing.includes(MARK_END)) {
    const start = existing.indexOf(MARK_START);
    const end = existing.indexOf(MARK_END) + MARK_END.length;
    return existing.slice(0, start) + section + existing.slice(end);
  }
  return `${existing.replace(/\n*$/, '')}${existing.trim() ? '\n\n' : ''}${section}\n`;
}

function readJson(project, rel) {
  const file = path.join(project, rel);
  return existsSync(file) ? JSON.parse(readFileSync(file, 'utf8')) : {};
}

const isOurs = (h) => JSON.stringify(h).includes(HOOK_TAG);

// Replace go-getter's entry in an event list (or remove it when entry is null), keeping everything else.
export function upsert(list, entry) {
  const kept = (list ?? []).filter((x) => !isOurs(x));
  return entry ? [...kept, entry] : kept;
}

function setEvent(obj, keys, entry) {
  const out = structuredClone(obj);
  let node = out;
  for (const k of keys.slice(0, -1)) node = node[k] ??= {};
  const last = keys[keys.length - 1];
  const next = upsert(node[last], entry);
  if (next.length) node[last] = next;
  else delete node[last];
  return out;
}

const json = (value) => ({ content: `${JSON.stringify(value, null, 2)}\n` });

// Host hook configs (tier 2). Each calls the shared runtime: `.go-getter/bin/go-getter hook <event> --host <id>`.
// `enabled`: tier-2 path guardrails exist (pre-tool hook). `session`: kms knowledge base present (session-start nudges).
// `stop`: the verification gate blocks "done" (stop hook; hosts that cannot block a stop get none).
export function hostHookOutputs(project, hosts, enabled, session = false, stop = false) {
  const cmd = (host, event = 'pre-tool') => `sh ${RUNNER} hook ${event} --host ${host}`;
  const out = {};
  // Hosts whose stop event can keep the agent working (capability hooks.blockStop) get the gate; the rest stay advisory.
  const caps = packageCapabilities();
  const canStop = (host) => stop && caps[host]?.hooks.blockStop === true;
  // Touch a host's hook file only to install our hooks, or to remove them from a file that already exists.
  const wanted = (rel) => enabled || session || stop || existsSync(path.join(project, rel));
  const ccLike = (host, event) => ({ matcher: '*', hooks: [{ type: 'command', command: cmd(host, event) }] });
  const plain = (host, event) => ({ hooks: [{ type: 'command', command: cmd(host, event) }] });
  // Sets or removes each of go-getter's events: [keys, entry-or-null].
  const events = (obj, list) => list.reduce((acc, [keys, entry]) => setEvent(acc, keys, entry), obj);
  for (const host of hosts) {
    if (host === 'claude-code' && wanted('.claude/settings.json')) {
      out['.claude/settings.json'] = json(events(readJson(project, '.claude/settings.json'), [
        [['hooks', 'PreToolUse'], enabled ? ccLike(host) : null],
        [['hooks', 'SessionStart'], session ? plain(host, 'session-start') : null],
        [['hooks', 'Stop'], canStop(host) ? plain(host, 'stop') : null],
      ]));
    }
    if (host === 'codex' && wanted('.codex/hooks.json')) {
      out['.codex/hooks.json'] = json(events(readJson(project, '.codex/hooks.json'), [
        [['hooks', 'PreToolUse'], enabled ? ccLike(host) : null],
        [['hooks', 'SessionStart'], session ? plain(host, 'session-start') : null],
        [['hooks', 'Stop'], canStop(host) ? plain(host, 'stop') : null],
      ]));
    }
    if (host === 'gemini-cli' && wanted('.gemini/settings.json')) {
      out['.gemini/settings.json'] = json(events(readJson(project, '.gemini/settings.json'), [
        [['hooks', 'BeforeTool'], enabled ? ccLike(host) : null],
        [['hooks', 'SessionStart'], session ? plain(host, 'session-start') : null],
        [['hooks', 'AfterAgent'], canStop(host) ? plain(host, 'stop') : null],
      ]));
    }
    if (host === 'cursor' && wanted('.cursor/hooks.json')) {
      out['.cursor/hooks.json'] = json({ version: 1, ...events(readJson(project, '.cursor/hooks.json'), [
        [['hooks', 'preToolUse'], enabled ? { command: cmd(host) } : null],
        [['hooks', 'sessionStart'], session ? { command: cmd(host, 'session-start') } : null],
        [['hooks', 'stop'], canStop(host) ? { command: cmd(host, 'stop') } : null],
      ]) });
    }
    if (host === 'copilot' && (enabled || session)) {
      const hooks = {};
      if (enabled) hooks.preToolUse = [{ type: 'command', bash: cmd(host), timeoutSec: 30 }];
      if (session) hooks.sessionStart = [{ type: 'command', bash: cmd(host, 'session-start'), timeoutSec: 30 }];
      out['.github/hooks/go-getter.json'] = json({ version: 1, hooks });
    }
    if ((host === 'kilo' || host === 'opencode') && enabled) {
      out[caps[host].hooks.config] = {
        content: `// Generated by go-getter apply; do not edit. Routes tool calls through go-getter's hook runtime (tier 2).
import { spawnSync } from 'node:child_process';

export const GoGetter = async () => ({
  'tool.execute.before': async (input, output) => {
    const res = spawnSync('sh', ['${RUNNER}', 'hook', 'pre-tool', '--host', '${host}'], {
      input: JSON.stringify({ tool_name: input.tool, tool_input: output.args }),
      encoding: 'utf8',
    });
    if (res.status === 2) throw new Error(res.stderr.trim() || 'blocked by go-getter guardrail');
  },
});
`,
      };
    }
  }
  return out;
}

const PACKAGE_ROOT = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..', '..');

function filesUnder(dir, base = dir) {
  return readdirSync(dir).sort().flatMap((n) => {
    const p = path.join(dir, n);
    return statSync(p).isDirectory() ? filesUnder(p, base) : [path.relative(base, p).split(path.sep).join('/')];
  });
}

// Project-local skills (plan 4.4b): the package's compiled skills and the support dirs they reference,
// for hosts without a plugin install that keeps them together (remote skill indexes carry no shared files).
export function projectSkillOutputs(packageRoot, hosts) {
  const plugin = path.join(packageRoot, 'plugins/go-getter');
  const out = {};
  for (const dir of ['skills', 'shared', 'templates']) {
    const src = path.join(plugin, dir);
    if (!existsSync(src)) continue;
    for (const f of filesUnder(src)) {
      if (dir === 'skills' && (f === 'index.json' || f === '.gitkeep')) continue;
      out[`.agents/${dir}/${f}`] = { content: readFileSync(path.join(src, f), 'utf8') };
    }
    if (hosts.includes('claude-code')) out[`.claude/${dir}`] = { symlink: `../.agents/${dir}` };
  }
  return out;
}

export function planApply(project, { hosts, skills, packageRoot = PACKAGE_ROOT } = {}) {
  const detected = detect(project);
  const targetHosts = hosts?.length ? hosts : detected.hostAgents;
  for (const h of targetHosts) if (!HOSTS.includes(h)) throw new Error(`unknown host "${h}"`);
  const entries = collectEnforcement(project);
  const tier2 = entries.some((e) => e.tier === 2);
  const isGate = (e) => e.parsed?.kind === 'builtin' && e.parsed.id === 'verify-gate';
  const preTool = entries.some((e) => e.tier === 2 && !isGate(e));
  const stop = entries.some((e) => e.tier === 2 && isGate(e));
  const tier3 = entries.some((e) => e.tier === 3);
  const outputs = { [RUNNER]: { content: runnerScript, mode: 0o755 } };

  const agentsMd = existsSync(path.join(project, 'AGENTS.md')) ? readFileSync(path.join(project, 'AGENTS.md'), 'utf8') : '# AGENTS.md\n';
  outputs['AGENTS.md'] = { content: withSection(agentsMd, guardrailSection(entries)) };
  if (targetHosts.includes('claude-code')) {
    const claude = path.join(project, 'CLAUDE.md');
    const isRegularFile = existsSync(claude) && !lstatSync(claude).isSymbolicLink();
    if (!isRegularFile) outputs['CLAUDE.md'] = { symlink: 'AGENTS.md' };
  }
  if (targetHosts.includes('gemini-cli')) {
    const settings = readJson(project, '.gemini/settings.json');
    const names = new Set([].concat(settings.context?.fileName ?? []));
    names.add('AGENTS.md');
    outputs['.gemini/settings.json'] = json({ ...settings, context: { ...settings.context, fileName: [...names].sort() } });
  }
  const hookOutputs = hostHookOutputs(project, targetHosts, preTool, detected.kms, stop);
  for (const [p, o] of Object.entries(hookOutputs)) {
    if (p === '.gemini/settings.json' && outputs[p]) {
      // Merge the hook change into the context.fileName change for the same file.
      const merged = { ...JSON.parse(o.content), context: JSON.parse(outputs[p].content).context };
      outputs[p] = json(merged);
    } else outputs[p] = o;
  }
  // Governance: switch off host prompt logging where the adopted decision requires it.
  const caps = packageCapabilities(packageRoot);
  for (const host of promptLoggingTargets(project, caps, targetHosts)) {
    const { file, key } = caps[host].telemetry.promptLogOff;
    const base = outputs[file] ? JSON.parse(outputs[file].content) : readJson(project, file);
    outputs[file] = json(setPath(base, key, false));
  }
  // Cost routing: prompt-cache lifetimes where the host has settings for them (decision 0032).
  const ttl = loadPolicy(project)?.cacheTtl;
  for (const host of ttl ? targetHosts : []) {
    const target = caps[host]?.routing.cacheTtl;
    if (!target) continue;
    let base = outputs[target.file] ? JSON.parse(outputs[target.file].content) : readJson(project, target.file);
    for (const [kind, value] of [['main', ttl.main], ['subagent', ttl.subagent]]) {
      if (value) for (const key of target[kind]) base = setPath(base, [key], value);
    }
    outputs[target.file] = json(base);
  }
  if (tier3) {
    outputs['.githooks/pre-push'] = { content: prePush, mode: 0o755 };
    if (detected.ci.includes('github-actions') || detected.git.remoteHost === 'github.com') {
      outputs['.github/workflows/go-getter-checks.yml'] = { content: ciWorkflow };
    }
  }
  const withSkills = skills ?? (targetHosts.includes('kilo') || targetHosts.includes('opencode'));
  if (withSkills) Object.assign(outputs, projectSkillOutputs(packageRoot, targetHosts));
  Object.assign(outputs, agentOutputs(project, targetHosts));
  const stale = staleAgentFiles(project, targetHosts, outputs);
  return { hosts: targetHosts, outputs, stale, tier2, tier3, skills: withSkills };
}

export function diffApply(project, plan) {
  const problems = [];
  for (const [rel, o] of Object.entries(plan.outputs)) {
    const file = path.join(project, rel);
    let stat;
    try {
      stat = lstatSync(file);
    } catch {
      problems.push(`missing: ${rel}`);
      continue;
    }
    if ('symlink' in o) {
      if (!stat.isSymbolicLink() || readlinkSync(file) !== o.symlink) problems.push(`differs: ${rel}`);
    } else if (stat.isSymbolicLink() || readFileSync(file, 'utf8') !== o.content) problems.push(`differs: ${rel}`);
  }
  for (const rel of plan.stale ?? []) problems.push(`stale: ${rel}`);
  return problems.sort();
}

export function writeApply(project, plan) {
  for (const [rel, o] of Object.entries(plan.outputs)) {
    const file = path.join(project, rel);
    mkdirSync(path.dirname(file), { recursive: true });
    if ('symlink' in o) {
      if (!existsSync(file)) symlinkSync(o.symlink, file);
      continue;
    }
    writeFileSync(file, o.content);
    if (o.mode) chmodSync(file, o.mode);
  }
  for (const rel of plan.stale ?? []) rmSync(path.join(project, rel), { force: true });
  if (plan.tier3) {
    try {
      execFileSync('git', ['config', 'core.hooksPath', '.githooks'], { cwd: project, stdio: 'ignore' });
    } catch {
      // not a git repository; the hook files are still written
    }
  }
  return Object.keys(plan.outputs).sort();
}
