// `go-getter apply` (plan 4.4): materializes guardrail enforcement into project-local files (decision 0021, output kind B).
// Outputs are planned first ({path: {content, mode?} | {symlink}}) so the same plan drives writing and drift checking.
import { existsSync, readFileSync, lstatSync, readlinkSync, mkdirSync, writeFileSync, symlinkSync, chmodSync, readdirSync, statSync, rmSync } from 'node:fs';
import { fileURLToPath } from 'node:url';
import { execFileSync } from 'node:child_process';
import path from 'node:path';
import { collectEnforcement } from './enforce.mjs';
import { detect } from './detect.mjs';
import { HOSTS } from './capabilities.mjs';
import { agentOutputs, staleAgentFiles } from './agents.mjs';
import { packageCapabilities, promptLoggingTargets, setPath } from './governance.mjs';
import { loadPolicy } from './routing/policy.mjs';
import { verifyConfig } from './verify.mjs';
import { otelConfig, otelReport, withOtel } from './telemetry/otel.mjs';

export const RUNNER = '.go-getter/bin/go-getter';
const MARK_START = '<!-- go-getter:start -->';
const MARK_END = '<!-- go-getter:end -->';
// Recognises go-getter's hook entries in both command shapes (the old relative `sh <runner> hook` and the walk-up one that quotes the path).
const HOOK_TAG = new RegExp(`${RUNNER.replaceAll('.', '\\.')}(\\\\")? hook`);
const NODE_FLOOR = 22;

const runnerScript = `#!/bin/sh
# Generated by go-getter apply; do not edit. Runs the go-getter CLI when Node >= ${NODE_FLOOR} is available,
# otherwise warns and exits 0 so enforcement degrades to advisory (decision 0019).
FLOOR=${NODE_FLOOR}
if ! command -v node >/dev/null 2>&1; then
  echo "go-getter: enforcement unavailable: Node >= $FLOOR not found" >&2
  exit 0
fi
MAJOR=$(node -p 'process.versions.node.split(".")[0]')
if [ "$MAJOR" -lt "$FLOOR" ]; then
  echo "go-getter: enforcement unavailable: Node $MAJOR < $FLOOR" >&2
  exit 0
fi
ROOT=$(git rev-parse --show-toplevel 2>/dev/null || pwd)
if [ -f "$ROOT/compiler/bin/go-getter.mjs" ] && grep -q '"name": "go-getter"' "$ROOT/package.json" 2>/dev/null; then
  exec node "$ROOT/compiler/bin/go-getter.mjs" "$@"
fi
exec npx --yes github:vivantel/go-getter "$@"
`;

const prePush = `#!/bin/sh
# Generated by go-getter apply; do not edit. Tier-3 guardrail checks before every push (decision 0009).
exec "$(git rev-parse --show-toplevel)/${RUNNER}" check --stage pre-push
`;

const CHECKOUT = 'actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1';
const SETUP_NODE = 'actions/setup-node@820762786026740c76f36085b0efc47a31fe5020 # v7.0.0';
// Dependency install per detected package manager; a package.json without a lockfile gets `npm install`.
const INSTALL = {
  npm: 'npm ci',
  pnpm: 'corepack enable && pnpm install --frozen-lockfile',
  yarn: 'corepack enable && yarn install --frozen-lockfile',
  bun: 'npm install --global bun && bun install --frozen-lockfile',
};
// A YAML plain scalar when that is unambiguous, else a double-quoted one (JSON strings are valid YAML).
const scalar = (s) => (/^[\w./][\w ./=@+&-]*$/.test(s) && !s.endsWith(' ') ? s : JSON.stringify(s));

// The generated GitHub Actions workflow: the tier-3 guardrail job (decision 0009) when `guardrails`, and one job per
// check placed in CI (`ci` or `both`, decision 0071). `node` is {version, install} for a Node project, else null.
export function ciWorkflow({ guardrails = true, checks = {}, node = null } = {}) {
  const lines = [
    '# Generated by go-getter apply; do not edit. Tier-3 guardrail checks (decision 0009) and CI-placed verification checks (decision 0071).',
    'name: go-getter checks',
    '',
    'on:',
    '  pull_request:',
    '  push:',
    '    branches: [main]',
    '',
    'permissions:',
    '  contents: read',
    '',
    'jobs:',
  ];
  if (guardrails) {
    lines.push(
      '  go-getter-checks:',
      '    runs-on: ubuntu-latest',
      '    steps:',
      `      - uses: ${CHECKOUT}`,
      '        with:',
      '          fetch-depth: 0',
      `      - uses: ${SETUP_NODE}`,
      '        with:',
      `          node-version: ${NODE_FLOOR}`,
      `      - run: sh ${RUNNER} check --stage ci`,
    );
  }
  for (const [name, command] of Object.entries(checks)) {
    if (lines.at(-1) !== 'jobs:') lines.push('');
    lines.push(`  verify-${name}:`, '    runs-on: ubuntu-latest', '    steps:', `      - uses: ${CHECKOUT}`);
    if (node) {
      lines.push(`      - uses: ${SETUP_NODE}`, '        with:', `          node-version: ${scalar(node.version)}`);
      if (node.install) lines.push(`      - run: ${scalar(node.install)}`);
    }
    lines.push(`      - run: ${scalar(command)}`);
  }
  return `${lines.join('\n')}\n`;
}

const onGitHub = (detected) => detected.ci.includes('github-actions') || detected.git.remoteHost === 'github.com';

// Coverage note for a project whose CI-placed checks get no generated jobs: only GitHub Actions has them (decision 0071).
export function ciChecksNote(project) {
  const names = Object.keys(verifyConfig(project).ci);
  if (!names.length || onGitHub(detect(project))) return null;
  return `note: verification checks placed in CI (${names.join(', ')}) get generated jobs on GitHub Actions only; run them in your CI provider (decision 0071).`;
}

function guardrailSection(entries) {
  const byGuardrail = new Map();
  for (const e of entries) {
    const g = byGuardrail.get(e.guardrail) ?? { title: e.title, tiers: new Set() };
    g.tiers.add(e.tier);
    byGuardrail.set(e.guardrail, g);
  }
  const groups = { 3: [], 2: [], 1: [] };
  for (const [id, g] of [...byGuardrail].sort()) groups[Math.max(...g.tiers)].push(`- ${g.title} (\`${id}\`)`);
  const lines = [MARK_START, '## Guardrails', '', 'Generated by `go-getter apply` from `docs/guardrails/`; do not edit this section.', ''];
  if (groups[3].length) lines.push('Checked by git hooks and CI:', '', ...groups[3], '');
  if (groups[2].length) lines.push('Blocked by host hooks where the host supports it:', '', ...groups[2], '');
  if (groups[1].length) lines.push('Advisory:', '', ...groups[1], '');
  lines.push(MARK_END);
  return lines.join('\n');
}

export function withSection(existing, section) {
  if (existing.includes(MARK_START) && existing.includes(MARK_END)) {
    const start = existing.indexOf(MARK_START);
    const end = existing.indexOf(MARK_END) + MARK_END.length;
    return existing.slice(0, start) + section + existing.slice(end);
  }
  return `${existing.replace(/\n*$/, '')}${existing.trim() ? '\n\n' : ''}${section}\n`;
}

function readJson(project, rel) {
  const file = path.join(project, rel);
  return existsSync(file) ? JSON.parse(readFileSync(file, 'utf8')) : {};
}

const isOurs = (h) => HOOK_TAG.test(JSON.stringify(h));

// Replace go-getter's entry in an event list (or remove it when entry is null), keeping everything else.
export function upsert(list, entry) {
  const kept = (list ?? []).filter((x) => !isOurs(x));
  return entry ? [...kept, entry] : kept;
}

function setEvent(obj, keys, entry) {
  const out = structuredClone(obj);
  let node = out;
  for (const k of keys.slice(0, -1)) node = node[k] ??= {};
  const last = keys[keys.length - 1];
  const next = upsert(node[last], entry);
  if (next.length) node[last] = next;
  else delete node[last];
  return out;
}

const json = (value) => ({ content: `${JSON.stringify(value, null, 2)}\n` });

// Host hook configs (tier 2). Each calls the shared runtime: `.go-getter/bin/go-getter hook <event> --host <id>`.
// `enabled`: tier-2 path guardrails exist (pre-tool hook). `session`: knowledge base present (session-start nudges).
// `stop`: the verification gate blocks "done" (stop hook; hosts that cannot block a stop get none).
export function hostHookOutputs(project, hosts, enabled, session = false, stop = false) {
  // A host may run hooks from a subdirectory: walk up to the project root that holds the runner and hand it to the
  // runtime as --project. Without a runner the hook warns and lets the call through (fail open, decision 0019).
  // The script is wrapped in `sh -c '...'` so it also works for a host that executes the command without a shell;
  // it therefore uses double quotes only.
  const cmd = (host, event = 'pre-tool') =>
    `sh -c '` +
    `d=$PWD; while [ ! -f "$d/${RUNNER}" ] && [ "$d" != / ]; do d=$(dirname "$d"); done; ` +
    `[ -f "$d/${RUNNER}" ] || { echo "go-getter: runner not found; hook skipped" >&2; exit 0; }; ` +
    `exec sh "$d/${RUNNER}" hook ${event} --host ${host} --project "$d"'`;
  const out = {};
  // Hosts whose stop event can keep the agent working (capability hooks.blockStop) get the gate; the rest stay advisory.
  const caps = packageCapabilities();
  const canStop = (host) => stop && caps[host]?.hooks.blockStop === true;
  // Tool-output redaction rides on the restricted-path guardrails, where the host can replace output (hooks.rewriteOutput).
  const canRedact = (host) => enabled && caps[host]?.hooks.rewriteOutput === true;
  // Touch a host's hook file only to install our hooks, or to remove them from a file that already exists.
  const wanted = (rel) => enabled || session || stop || existsSync(path.join(project, rel));
  const ccLike = (host, event) => ({ matcher: '*', hooks: [{ type: 'command', command: cmd(host, event) }] });
  const plain = (host, event) => ({ hooks: [{ type: 'command', command: cmd(host, event) }] });
  // Sets or removes each of go-getter's events: [keys, entry-or-null].
  const events = (obj, list) => list.reduce((acc, [keys, entry]) => setEvent(acc, keys, entry), obj);
  for (const host of hosts) {
    if (host === 'claude-code' && wanted('.claude/settings.json')) {
      out['.claude/settings.json'] = json(events(readJson(project, '.claude/settings.json'), [
        [['hooks', 'PreToolUse'], enabled ? ccLike(host) : null],
        [['hooks', 'PostToolUse'], canRedact(host) ? ccLike(host, 'post-tool') : null],
        [['hooks', 'SessionStart'], session ? plain(host, 'session-start') : null],
        [['hooks', 'Stop'], canStop(host) ? plain(host, 'stop') : null],
      ]));
    }
    if (host === 'codex' && wanted('.codex/hooks.json')) {
      out['.codex/hooks.json'] = json(events(readJson(project, '.codex/hooks.json'), [
        [['hooks', 'PreToolUse'], enabled ? ccLike(host) : null],
        [['hooks', 'PostToolUse'], canRedact(host) ? ccLike(host, 'post-tool') : null],
        [['hooks', 'SessionStart'], session ? plain(host, 'session-start') : null],
        [['hooks', 'Stop'], canStop(host) ? plain(host, 'stop') : null],
      ]));
    }
    if (host === 'gemini-cli' && wanted('.gemini/settings.json')) {
      out['.gemini/settings.json'] = json(events(readJson(project, '.gemini/settings.json'), [
        [['hooks', 'BeforeTool'], enabled ? ccLike(host) : null],
        [['hooks', 'AfterTool'], canRedact(host) ? ccLike(host, 'post-tool') : null],
        [['hooks', 'SessionStart'], session ? plain(host, 'session-start') : null],
        [['hooks', 'AfterAgent'], canStop(host) ? plain(host, 'stop') : null],
      ]));
    }
    if (host === 'cursor' && wanted('.cursor/hooks.json')) {
      out['.cursor/hooks.json'] = json({ version: 1, ...events(readJson(project, '.cursor/hooks.json'), [
        [['hooks', 'preToolUse'], enabled ? { command: cmd(host) } : null],
        [['hooks', 'sessionStart'], session ? { command: cmd(host, 'session-start') } : null],
        [['hooks', 'stop'], canStop(host) ? { command: cmd(host, 'stop') } : null],
      ]) });
    }
    if (host === 'copilot' && (enabled || session)) {
      const hooks = {};
      if (enabled) hooks.preToolUse = [{ type: 'command', bash: cmd(host), timeoutSec: 30 }];
      if (canRedact(host)) hooks.postToolUse = [{ type: 'command', bash: cmd(host, 'post-tool'), timeoutSec: 30 }];
      if (session) hooks.sessionStart = [{ type: 'command', bash: cmd(host, 'session-start'), timeoutSec: 30 }];
      out['.github/hooks/go-getter.json'] = json({ version: 1, hooks });
    }
    if ((host === 'kilo' || host === 'opencode') && enabled) {
      out[caps[host].hooks.config] = {
        content: `// Generated by go-getter apply; do not edit. Routes tool calls through go-getter's hook runtime (tier 2).
import { spawnSync } from 'node:child_process';
import { existsSync } from 'node:fs';
import path from 'node:path';

const RUNNER = '${RUNNER}';
// The host may run from a subdirectory: walk up to the project root that holds the runner.
const findRoot = (from) => {
  for (let d = from; ; d = path.dirname(d)) {
    if (existsSync(path.join(d, RUNNER))) return d;
    if (path.dirname(d) === d) return null;
  }
};

export const GoGetter = async () => ({
  'tool.execute.before': async (input, output) => {
    const root = findRoot(process.cwd());
    if (!root) return; // fail open: no runner above the working directory (decision 0019)
    const res = spawnSync('sh', [path.join(root, RUNNER), 'hook', 'pre-tool', '--host', '${host}', '--project', root], {
      input: JSON.stringify({ tool_name: input.tool, tool_input: output.args }),
      encoding: 'utf8',
    });
    if (res.status === 2) throw new Error(res.stderr.trim() || 'blocked by go-getter guardrail');
  },${canRedact(host) ? `
  // Tool-output redaction: the runtime answers { output } only when it redacted something; any failure keeps the result.
  'tool.execute.after': async (input, output) => {
    const root = findRoot(process.cwd());
    if (!root) return;
    const res = spawnSync('sh', [path.join(root, RUNNER), 'hook', 'post-tool', '--host', '${host}', '--project', root], {
      input: JSON.stringify({ tool_name: input.tool, tool_response: output.output }),
      encoding: 'utf8',
    });
    try {
      const answer = res.status === 0 && res.stdout ? JSON.parse(res.stdout) : null;
      if (typeof answer?.output === 'string') output.output = answer.output;
    } catch {
      // fail open (decision 0019)
    }
  },` : ''}
});
`,
      };
    }
  }
  return out;
}

const PACKAGE_ROOT = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..', '..');

function filesUnder(dir, base = dir) {
  return readdirSync(dir).sort().flatMap((n) => {
    const p = path.join(dir, n);
    return statSync(p).isDirectory() ? filesUnder(p, base) : [path.relative(base, p).split(path.sep).join('/')];
  });
}

// Project-local skills (plan 4.4b): the package's compiled skills and the support dirs they reference,
// for hosts without a plugin install that keeps them together (remote skill indexes carry no shared files).
export function projectSkillOutputs(packageRoot, hosts) {
  const plugin = path.join(packageRoot, 'plugins/go-getter');
  const out = {};
  for (const dir of ['skills', 'shared', 'templates']) {
    const src = path.join(plugin, dir);
    if (!existsSync(src)) continue;
    for (const f of filesUnder(src)) {
      if (dir === 'skills' && (f === 'index.json' || f === '.gitkeep')) continue;
      out[`.agents/${dir}/${f}`] = { content: readFileSync(path.join(src, f), 'utf8') };
    }
    if (hosts.includes('claude-code')) out[`.claude/${dir}`] = { symlink: `../.agents/${dir}` };
  }
  return out;
}

export function planApply(project, { hosts, skills, packageRoot = PACKAGE_ROOT } = {}) {
  const detected = detect(project);
  const targetHosts = hosts?.length ? hosts : detected.hostAgents;
  for (const h of targetHosts) if (!HOSTS.includes(h)) throw new Error(`unknown host "${h}"`);
  const entries = collectEnforcement(project);
  const tier2 = entries.some((e) => e.tier === 2);
  const isGate = (e) => e.parsed?.kind === 'builtin' && e.parsed.id === 'verify-gate';
  const preTool = entries.some((e) => e.tier === 2 && !isGate(e));
  const stop = entries.some((e) => e.tier === 2 && isGate(e));
  const tier3 = entries.some((e) => e.tier === 3);
  const outputs = { [RUNNER]: { content: runnerScript, mode: 0o755 } };

  const agentsMd = existsSync(path.join(project, 'AGENTS.md')) ? readFileSync(path.join(project, 'AGENTS.md'), 'utf8') : '# AGENTS.md\n';
  outputs['AGENTS.md'] = { content: withSection(agentsMd, guardrailSection(entries)) };
  if (targetHosts.includes('claude-code')) {
    const claude = path.join(project, 'CLAUDE.md');
    const isRegularFile = existsSync(claude) && !lstatSync(claude).isSymbolicLink();
    if (!isRegularFile) outputs['CLAUDE.md'] = { symlink: 'AGENTS.md' };
  }
  if (targetHosts.includes('gemini-cli')) {
    const settings = readJson(project, '.gemini/settings.json');
    const names = new Set([].concat(settings.context?.fileName ?? []));
    names.add('AGENTS.md');
    outputs['.gemini/settings.json'] = json({ ...settings, context: { ...settings.context, fileName: [...names].sort() } });
  }
  const hookOutputs = hostHookOutputs(project, targetHosts, preTool, detected.knowledgeBase, stop);
  for (const [p, o] of Object.entries(hookOutputs)) {
    if (p === '.gemini/settings.json' && outputs[p]) {
      // Merge the hook change into the context.fileName change for the same file.
      const merged = { ...JSON.parse(o.content), context: JSON.parse(outputs[p].content).context };
      outputs[p] = json(merged);
    } else outputs[p] = o;
  }
  // Governance: switch off host prompt logging where the adopted decision requires it.
  const caps = packageCapabilities(packageRoot);
  for (const host of promptLoggingTargets(project, caps, targetHosts)) {
    const { file, key } = caps[host].telemetry.promptLogOff;
    const base = outputs[file] ? JSON.parse(outputs[file].content) : readJson(project, file);
    outputs[file] = json(setPath(base, key, false));
  }
  // Telemetry: host OpenTelemetry settings where the project config accepts them (draft decision 0087).
  const otel = otelReport(project, targetHosts);
  const { endpoint } = otelConfig(project);
  for (const [host, r] of Object.entries(otel ?? {})) {
    if (r.status !== 'emitted') continue;
    const base = outputs[r.file] ? JSON.parse(outputs[r.file].content) : readJson(project, r.file);
    outputs[r.file] = json(withOtel(host, base, endpoint));
  }
  // Cost routing: prompt-cache lifetimes where the host has settings for them (decision 0032).
  const ttl = loadPolicy(project)?.cacheTtl;
  for (const host of ttl ? targetHosts : []) {
    const target = caps[host]?.routing.cacheTtl;
    if (!target) continue;
    let base = outputs[target.file] ? JSON.parse(outputs[target.file].content) : readJson(project, target.file);
    for (const [kind, value] of [['main', ttl.main], ['subagent', ttl.subagent]]) {
      if (value) for (const key of target[kind]) base = setPath(base, [key], value);
    }
    outputs[target.file] = json(base);
  }
  if (tier3) outputs['.githooks/pre-push'] = { content: prePush, mode: 0o755 };
  const ciChecks = verifyConfig(project).ci;
  if ((tier3 || Object.keys(ciChecks).length) && onGitHub(detected)) {
    const node = existsSync(path.join(project, 'package.json'))
      ? { version: detected.nodeVersion ?? 'lts/*', install: INSTALL[['pnpm', 'yarn', 'bun', 'npm'].find((m) => detected.packageManagers.includes(m))] ?? 'npm install' }
      : null;
    outputs['.github/workflows/go-getter-checks.yml'] = { content: ciWorkflow({ guardrails: tier3, checks: ciChecks, node }) };
  }
  const withSkills = skills ?? (targetHosts.includes('kilo') || targetHosts.includes('opencode'));
  if (withSkills) Object.assign(outputs, projectSkillOutputs(packageRoot, targetHosts));
  Object.assign(outputs, agentOutputs(project, targetHosts));
  const stale = staleAgentFiles(project, targetHosts, outputs);
  return { hosts: targetHosts, outputs, stale, tier2, tier3, skills: withSkills, otel };
}

export function diffApply(project, plan) {
  const problems = [];
  for (const [rel, o] of Object.entries(plan.outputs)) {
    const file = path.join(project, rel);
    let stat;
    try {
      stat = lstatSync(file);
    } catch {
      problems.push(`missing: ${rel}`);
      continue;
    }
    if ('symlink' in o) {
      if (!stat.isSymbolicLink() || readlinkSync(file) !== o.symlink) problems.push(`differs: ${rel}`);
    } else if (stat.isSymbolicLink() || readFileSync(file, 'utf8') !== o.content) problems.push(`differs: ${rel}`);
  }
  for (const rel of plan.stale ?? []) problems.push(`stale: ${rel}`);
  return problems.sort();
}

export function writeApply(project, plan) {
  for (const [rel, o] of Object.entries(plan.outputs)) {
    const file = path.join(project, rel);
    mkdirSync(path.dirname(file), { recursive: true });
    if ('symlink' in o) {
      if (!existsSync(file)) symlinkSync(o.symlink, file);
      continue;
    }
    writeFileSync(file, o.content);
    if (o.mode) chmodSync(file, o.mode);
  }
  for (const rel of plan.stale ?? []) rmSync(path.join(project, rel), { force: true });
  if (plan.tier3) {
    try {
      execFileSync('git', ['config', 'core.hooksPath', '.githooks'], { cwd: project, stdio: 'ignore' });
    } catch {
      // not a git repository; the hook files are still written
    }
  }
  return Object.keys(plan.outputs).sort();
}
