// `go-getter refs` (plan A.1): candidate `Refs:` artifacts for a diff, in a must-have and a nice-to-have group,
// each with a one-line reason that never repeats the artifact's title. Read-only; the attribute skill confirms the list.
import { execFileSync } from 'node:child_process';
import { readFileSync, readdirSync, existsSync } from 'node:fs';
import path from 'node:path';
import { parseFrontmatter } from './frontmatter.mjs';
import { ARTIFACT_TYPES } from './artifacts.mjs';
import { parseRun } from './packs.mjs';
import { matchesAny } from './glob.mjs';
import { cleanGitEnv } from './git-env.mjs';
import { changesTouched, listChanges } from './spec-tools.mjs';

const ARTIFACT_PATH = /^docs\/(facts|decisions|guardrails|skills)\/(?:archive\/)?(?!INDEX\.md$)[^/]+\.md$/;
const PATH_ARGS = ['path', 'paths', 'file', 'files', 'patterns'];
const GENERATED_FROM = /Generated by go-getter apply from ([0-9a-z][0-9a-z-]*)/;
const EXPIRY_DAYS = 30;

const git = (cwd, ...args) => execFileSync('git', args, { cwd, encoding: 'utf8', env: cleanGitEnv(process.env), stdio: ['ignore', 'pipe', 'pipe'] });

// Every artifact under docs/<type>/ and docs/<type>/archive/, keyed by id.
function loadArtifacts(root) {
  const byId = new Map();
  for (const type of ARTIFACT_TYPES) {
    for (const dir of [path.join('docs', type), path.join('docs', type, 'archive')]) {
      if (!existsSync(path.join(root, dir))) continue;
      for (const name of readdirSync(path.join(root, dir)).sort()) {
        if (!name.endsWith('.md') || name === 'INDEX.md') continue;
        const file = `${dir}/${name}`.split(path.sep).join('/');
        const body = readFileSync(path.join(root, file), 'utf8');
        let data = {};
        try {
          data = parseFrontmatter(body).data;
        } catch {
          // An unparsable artifact is still a candidate by path; lint reports the syntax.
        }
        byId.set(name.slice(0, -3), { id: name.slice(0, -3), type, file, data, body });
      }
    }
  }
  return byId;
}

// Changed paths as [{status: A|M|D|R, path, from?}] for the chosen diff.
export function changedFiles(root, { staged = false, base } = {}) {
  const range = base ? [`${base}...HEAD`] : staged ? ['--cached'] : ['HEAD'];
  return git(root, 'diff', '--name-status', '-M', ...range)
    .split('\n')
    .filter(Boolean)
    .map((line) => {
      const [status, a, b] = line.split('\t');
      return status.startsWith('R') ? { status: 'R', path: b, from: a } : { status: status[0], path: a };
    });
}

function diffText(root, file, { staged = false, base } = {}) {
  const range = base ? [`${base}...HEAD`] : staged ? ['--cached'] : ['HEAD'];
  return git(root, 'diff', '-U0', ...range, '--', file);
}

const list = (v) => (v == null ? [] : Array.isArray(v) ? v : [v]).map(String).filter(Boolean);
const csv = (v) => list(v).flatMap((s) => s.split(',')).map((s) => s.trim()).filter(Boolean);
const packOf = (a) => String(a?.data['go-getter']?.['generated-by'] ?? '').split('@')[0] || null;

// Path globs an artifact's enforcement runs name, and its restricted-paths data.
function namedPaths(a) {
  const named = [];
  for (const e of a.data['go-getter']?.enforcement ?? []) {
    if (!e?.run) continue;
    let parsed;
    try {
      parsed = parseRun(String(e.run));
    } catch {
      continue;
    }
    if (parsed.kind === 'builtin') for (const k of PATH_ARGS) named.push(...csv(parsed.args[k]).map((p) => ({ p, via: 'check' })));
    else named.push(...parsed.command.split(/\s+/).filter((t) => /[/.]/.test(t) && !/^-/.test(t)).map((p) => ({ p, via: 'check' })));
  }
  const restricted = a.data['go-getter']?.['restricted-paths'];
  for (const r of Array.isArray(restricted) ? restricted : [restricted]) {
    named.push(...csv(typeof r === 'object' && r ? r.path : r).map((p) => ({ p, via: 'restricted' })));
  }
  return named;
}

// Per type: tags carried by more than half of its active artifacts, plus those marked "(umbrella)" in docs/skills/tags.md.
function umbrellaTags(root, artifacts) {
  const marked = [];
  const file = path.join(root, 'docs/skills/tags.md');
  if (existsSync(file)) for (const m of readFileSync(file, 'utf8').matchAll(/^([a-z0-9][a-z0-9-]*) — .*\(umbrella\)/gm)) marked.push(m[1]);
  const byType = {};
  for (const type of ARTIFACT_TYPES) {
    const active = artifacts.filter((a) => a.type === type && a.data.status === 'active');
    const counts = new Map();
    for (const a of active) for (const t of new Set(list(a.data.tags))) counts.set(t, (counts.get(t) ?? 0) + 1);
    byType[type] = new Set([...marked, ...[...counts].filter(([, n]) => n * 2 > active.length).map(([t]) => t)]);
  }
  return byType;
}

function leadingDate(v) {
  const m = /^(\d{4}-\d{2}-\d{2})/.exec(String(v ?? ''));
  return m ? m[1] : null;
}

// The slug of the current branch (`type/slug` gives `slug`), or null when detached.
function branchSlug(root) {
  try {
    const branch = git(root, 'branch', '--show-current').trim();
    return branch ? branch.slice(branch.indexOf('/') + 1) : null;
  } catch {
    return null;
  }
}

// Returns { must: [{path, id, reason}], nice: [{path, id, reason}] }.
export function suggestRefs(root, { staged = false, base, today = new Date().toISOString().slice(0, 10) } = {}) {
  const byId = loadArtifacts(root);
  const artifacts = [...byId.values()];
  const byNumber = new Map(artifacts.filter((a) => /^\d{4}-/.test(a.id)).map((a) => [`${a.type}/${a.id.slice(0, 4)}`, a]));
  const changes = changedFiles(root, { staged, base }).sort((x, y) => x.path.localeCompare(y.path));
  const must = new Map();
  const nice = new Map();
  const add = (group, key, entry) => {
    if (!must.has(key) && !nice.has(key)) group.set(key, entry);
  };
  const addArtifact = (group, a, reason) => a && add(group, a.file, { path: a.file, id: a.id, reason });

  // Artifacts added or changed in the diff.
  const added = [];
  for (const c of changes) {
    if (c.status === 'D' || !ARTIFACT_PATH.test(c.path)) continue;
    const a = byId.get(path.basename(c.path, '.md'));
    if (!a) continue;
    if (c.status === 'A') added.push(a);
    addArtifact(must, a, c.status === 'A' ? 'added in this diff' : c.status === 'R' ? `moved from ${c.from} in this diff` : 'changed in this diff');
  }

  // Spec-tool changes (decision 0075): a change folder the diff touches, found by path. The branch slug is only a hint.
  const touched = changesTouched(changes.filter((c) => c.status !== 'D').map((c) => c.path));
  for (const c of touched) add(must, c.folder, { path: c.folder, id: null, reason: 'change folder touched in this diff' });
  const slug = branchSlug(root);
  if (slug) {
    for (const c of listChanges(root).filter((x) => x.id === slug)) add(nice, c.folder, { path: c.folder, id: null, reason: 'branch slug matches this change' });
  }

  // The plan step the change completes.
  for (const c of changes) {
    if (c.status === 'D' || !/^docs\/plans\/.+\.md$/.test(c.path)) continue;
    const lines = diffText(root, c.path, { staged, base }).split('\n');
    const was = new Set(lines.filter((l) => /^-### \S+ .* — \[[^x]\]/.test(l)).map((l) => l.split(' ')[1]));
    const done = lines.filter((l) => /^\+### \S+ .* — \[x\]/.test(l)).map((l) => l.split(' ')[1]).filter((id) => was.has(id));
    if (done.length) add(must, c.path, { path: c.path, id: null, reason: `completes step ${done.join(', ')}` });
  }

  // Decisions whose pack output the diff regenerates (a changed file generated from an artifact of that pack).
  for (const c of changes) {
    if (c.status === 'D' || ARTIFACT_PATH.test(c.path) || !existsSync(path.join(root, c.path))) continue;
    const source = byId.get(GENERATED_FROM.exec(readFileSync(path.join(root, c.path), 'utf8'))?.[1]);
    if (!source) continue;
    const pack = packOf(source);
    const inputs = pack ? artifacts.filter((a) => a.type === 'decisions' && a.data.status === 'active' && packOf(a) === pack) : [source];
    for (const a of inputs) addArtifact(must, a, `${c.path} is generated from it${pack ? ` (${pack} pack)` : ''}`);
  }

  // Decisions and guardrails whose enforcement runs or restricted-paths data name a changed path.
  for (const a of artifacts) {
    if (a.data.status !== 'active' || !['decisions', 'guardrails'].includes(a.type)) continue;
    const named = namedPaths(a);
    for (const c of changes) {
      const hit = named.find(({ p }) => matchesAny(c.path, [p]));
      if (hit) {
        addArtifact(must, a, hit.via === 'restricted' ? `restricts ${c.path}` : `its check covers ${c.path}`);
        break;
      }
    }
  }

  // A decision that an added decision supersedes.
  for (const a of added.filter((x) => x.type === 'decisions')) {
    const prose = [...a.body.matchAll(/\bSupersedes ((?:\d{4})(?:(?:, | and )\d{4})*)/g)].flatMap((m) => m[1].match(/\d{4}/g));
    const old = [
      ...list(a.data.supersedes).map((id) => byId.get(id) ?? byNumber.get(`decisions/${id.slice(0, 4)}`)),
      ...prose.map((n) => byNumber.get(`decisions/${n}`)),
      ...artifacts.filter((x) => x.type === 'decisions' && x.data['superseded-by'] === a.id),
    ];
    for (const o of old) if (o && o.id !== a.id) addArtifact(must, o, `superseded by ${a.id}`);
  }

  // Nice-to-have: one hop from each must-have.
  const mustArtifacts = [...must.values()].map((m) => m.id && byId.get(m.id)).filter(Boolean);
  for (const a of mustArtifacts) {
    for (const t of [...list(a.data['governed-by']), ...list(a.data['grounded-in'])]) {
      addArtifact(nice, byId.get(t), `${list(a.data['governed-by']).includes(t) ? 'governs' : 'grounds'} ${a.id}`);
    }
  }
  const umbrella = umbrellaTags(root, artifacts);
  const limit = new Date(Date.parse(`${today}T00:00:00Z`) + EXPIRY_DAYS * 86400000).toISOString().slice(0, 10);
  for (const a of mustArtifacts) {
    const tags = new Set(list(a.data.tags).filter((t) => !umbrella[a.type].has(t)));
    for (const f of artifacts) {
      if (f.type !== 'facts' || f.data.status !== 'active') continue;
      const expires = leadingDate(f.data.expires);
      if (!expires || expires > limit) continue;
      const linked = list(f.data['governed-by']).includes(a.id) || list(a.data['governed-facts']).includes(f.id) || list(f.data.tags).some((t) => tags.has(t));
      if (linked) addArtifact(nice, f, `expires ${expires}; re-check before relying on it`);
    }
  }
  for (const a of mustArtifacts) {
    const tags = list(a.data.tags).filter((t) => !umbrella[a.type].has(t));
    for (const s of artifacts) {
      if (s.type !== a.type || s.id === a.id || s.data.status !== 'active') continue;
      const shared = tags.find((t) => list(s.data.tags).includes(t));
      if (shared) addArtifact(nice, s, `shares tag ${shared} with ${a.id}`);
    }
  }
  return { must: [...must.values()], nice: [...nice.values()] };
}

export function formatRefs({ must, nice }) {
  const group = (name, rows) => [`${name}:`, ...(rows.length ? rows.map((r) => `  ${r.path} — ${r.reason}`) : ['  (none)'])];
  return [...group('Must-have', must), ...group('Nice-to-have', nice)].join('\n');
}
