// Runbook spike (decision 0104, plan docs/plans/runbook-spike.md): one on-demand skill per guardrail that inlines the
// norm, the steps of the procedures that operationalize it and the facts it is grounded in. Generated, never edited.
import { readFileSync, readdirSync, existsSync } from 'node:fs';
import path from 'node:path';
import { parseFrontmatter } from './frontmatter.mjs';
import { ARTIFACT_TYPES } from './artifacts.mjs';

export const runbookPath = (guardrailId) => `docs/runbooks/${guardrailId}/SKILL.md`;

const list = (v) => (v == null ? [] : Array.isArray(v) ? v : [v]).map(String).filter(Boolean);

// Every artifact under docs/<type>/ and docs/<type>/archive/, keyed by id.
function load(root) {
  const byId = new Map();
  for (const type of ARTIFACT_TYPES) {
    for (const dir of [path.join('docs', type), path.join('docs', type, 'archive')]) {
      if (!existsSync(path.join(root, dir))) continue;
      for (const name of readdirSync(path.join(root, dir)).sort()) {
        if (!name.endsWith('.md') || name === 'INDEX.md') continue;
        const { data, body } = parseFrontmatter(readFileSync(path.join(root, dir, name), 'utf8'));
        byId.set(name.slice(0, -3), { id: name.slice(0, -3), type, data, body });
      }
    }
  }
  return byId;
}

// The body without its leading `## Guardrail` / `## Procedure` heading.
const content = (body) => body.trim().replace(/^## (?:Guardrail|Procedure)\s*\n/, '').trim();

export function buildRunbook(root, guardrailId) {
  const byId = load(root);
  const guardrail = byId.get(guardrailId);
  if (!guardrail || guardrail.type !== 'guardrails') throw new Error(`runbook: no guardrail "${guardrailId}"`);
  const procedures = [...byId.values()].filter((a) => a.type === 'skills' && list(a.data.operationalizes).includes(guardrailId));
  if (!procedures.length) throw new Error(`runbook: guardrail "${guardrailId}" has no procedure that operationalizes it`);
  const grounded = list(guardrail.data['grounded-in']).map((id) => {
    const a = byId.get(id);
    if (!a) throw new Error(`runbook: "${guardrailId}" is grounded in "${id}", which does not exist`);
    return a;
  });
  const facts = grounded.filter((a) => a.type === 'facts');
  const named = grounded.filter((a) => a.type !== 'facts');
  const sources = [guardrail, ...procedures, ...facts].map((a) => a.id);
  const lines = [
    '---',
    `name: ${guardrailId}`,
    `description: Use when the task involves: ${guardrail.data.title}.`,
    '---',
    '',
    `<!-- Generated by go-getter runbook from ${sources.join(', ')}; do not edit. -->`,
    '',
    '## Norm',
    '',
    content(guardrail.body),
    '',
    '## Steps',
    '',
  ];
  for (const p of procedures) lines.push(...(procedures.length > 1 ? [`### ${p.data.title}`, ''] : []), content(p.body), '');
  if (facts.length) {
    lines.push('## Facts', '');
    for (const f of facts) lines.push(`### ${f.data.title}`, '', content(f.body), '');
  }
  if (named.length) lines.push('## Grounded in', '', ...named.map((a) => `- ${a.id}`), '');
  return `${lines.join('\n').replace(/\n+$/, '')}\n`;
}

// { ok, message }: the committed runbook equals a fresh build.
export function checkRunbook(root, guardrailId) {
  const file = path.join(root, runbookPath(guardrailId));
  if (!existsSync(file)) return { ok: false, message: `${runbookPath(guardrailId)} does not exist; run go-getter runbook build ${guardrailId}` };
  return readFileSync(file, 'utf8') === buildRunbook(root, guardrailId)
    ? { ok: true }
    : { ok: false, message: `${runbookPath(guardrailId)} is out of date; run go-getter runbook build ${guardrailId}` };
}
