import { test } from 'node:test';
import assert from 'node:assert/strict';
import { mkdtempSync, mkdirSync, writeFileSync, readFileSync, readdirSync, rmSync, existsSync, realpathSync } from 'node:fs';
import { tmpdir } from 'node:os';
import path from 'node:path';
import { fileURLToPath } from 'node:url';
import { execFileSync, spawnSync } from 'node:child_process';
import { loadPack, loadPackSchema, validatePack } from '../src/packs.mjs';
import { planRender, applyRender } from '../src/render.mjs';
import { planReconfigure, applyReconfigure } from '../src/reconfigure.mjs';
import { planApply, writeApply, diffApply } from '../src/apply.mjs';
import { readRoster } from '../src/agents.mjs';
import { runTier3 } from '../src/enforce.mjs';
import { HOSTS, loadCapabilities } from '../src/capabilities.mjs';
import { newWorktree, listWorktrees, cleanWorktrees, planClean } from '../src/worktree.mjs';

const root = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..', '..');
const cli = path.join(root, 'compiler/bin/go-getter.mjs');
const pack = loadPack(path.join(root, 'src/packs/orchestration/pack.json'));
const recommended = Object.fromEntries(pack.questions.map((q) => [q.id, q.options ? q.options.find((o) => o.recommended).id : q.default]));
const base = { acceptedBy: 't', date: '2026-10-05' };

function project(answers = recommended) {
  const dir = realpathSync(mkdtempSync(path.join(tmpdir(), 'gg-orch-')));
  mkdirSync(path.join(dir, 'docs/skills'), { recursive: true });
  writeFileSync(path.join(dir, 'docs/skills/tags.md'), '# Tags\n\npractice-packs — x\nagent-roles — x\nharness — x\nguardrail — x\n');
  applyRender({ root: dir, plan: planRender({ root: dir, pack, answers, ...base }) });
  return dir;
}

const read = (dir, rel) => readFileSync(path.join(dir, rel), 'utf8');

test('the orchestration pack is valid and covers component 10', () => {
  assert.deepEqual(validatePack(loadPackSchema(root), pack, { dirName: 'orchestration' }), []);
  assert.deepEqual(pack.components, [10]);
});

test('every answer renders, and the roster is recoverable from the decisions', () => {
  for (const q of pack.questions.filter((x) => x.options)) {
    for (const o of q.options) {
      const answers = { ...recommended, [q.id]: o.id };
      // Questions behind a `when` need their parent answer; keep the dependent ones consistent.
      if (q.id === 'isolation' && o.id !== 'worktree-per-task') delete answers['worktree-location'];
      if (q.id === 'roster' && o.id === 'no-roles') delete answers.reviewer;
      const dir = project(answers);
      const roster = readRoster(dir);
      assert.equal(roster.roles.length, answers.roster === 'five-roles' ? 5 : answers.roster === 'no-roles' ? 0 : 2, `${q.id}=${o.id}`);
      rmSync(dir, { recursive: true, force: true });
    }
  }
});

test('the recommended answers record roles with task classes and shared contract text', () => {
  const dir = project();
  const roster = readRoster(dir);
  assert.deepEqual(roster.roles.map((r) => [r.id, r['task-class'], r.access]), [
    ['planner', 'plan', 'read-only'],
    ['explorer', 'explore', 'read-only'],
    ['implementer', 'implement', 'write'],
    ['reviewer', 'review', 'read-only'],
    ['tester', 'debug', 'write'],
  ]);
  assert.match(roster.handoff, /evidence/);
  assert.match(roster.escalation, /guardrail denies/);
  rmSync(dir, { recursive: true, force: true });
});

test('apply --hosts all emits one agent file per role per host in each host format', () => {
  const dir = project();
  const caps = loadCapabilities(root);
  const plan = planApply(dir, { hosts: HOSTS, skills: false });
  writeApply(dir, plan);
  for (const host of HOSTS) {
    const { dir: agentDir, extension } = caps[host].agents;
    const files = readdirSync(path.join(dir, agentDir)).filter((f) => f.endsWith(extension)).sort();
    assert.deepEqual(files, ['explorer', 'implementer', 'planner', 'reviewer', 'tester'].map((r) => `${r}${extension}`), host);
  }
  const reviewer = (host) => read(dir, `${caps[host].agents.dir}/reviewer${caps[host].agents.extension}`);
  const implementer = (host) => read(dir, `${caps[host].agents.dir}/implementer${caps[host].agents.extension}`);

  assert.match(reviewer('claude-code'), /^---\nname: reviewer\ndescription: .*\ntools: Read, Grep, Glob\n---\n/);
  assert.doesNotMatch(implementer('claude-code'), /^tools:/m);
  assert.match(reviewer('codex'), /^# Generated by go-getter apply .* role=reviewer task-class=review\nname = "reviewer"\n/);
  assert.match(reviewer('codex'), /sandbox_mode = "read-only"/);
  assert.match(implementer('codex'), /sandbox_mode = "workspace-write"/);
  assert.match(reviewer('kilo'), /mode: subagent\npermission:\n {2}edit: deny\n {2}bash: deny\n---/);
  assert.doesNotMatch(implementer('kilo'), /permission:/);
  assert.match(reviewer('cursor'), /\nreadonly: true\n/);
  assert.match(reviewer('gemini-cli'), /\nkind: local\ntools: \["read_file", "list_directory", "glob", "grep_search"\]\n/);
  assert.match(reviewer('copilot'), /\ntools: \["read", "search"\]\n/);
  for (const host of HOSTS) {
    assert.match(reviewer(host), /Do not modify files; report findings only\./, host);
    assert.match(reviewer(host), /Handoff: .*evidence/, host);
    assert.match(reviewer(host), /task-class=review/, host);
  }
  // Codex developer_instructions is a TOML basic string: it must round-trip through JSON.
  const line = reviewer('codex').split('\n').find((l) => l.startsWith('developer_instructions = '));
  assert.match(JSON.parse(line.slice('developer_instructions = '.length)), /^Review the change/);

  assert.deepEqual(diffApply(dir, planApply(dir, { hosts: HOSTS, skills: false })), []);
  rmSync(dir, { recursive: true, force: true });
});

test('a reviewer with write access gets no tool restriction and its note', () => {
  const dir = project({ ...recommended, reviewer: 'trivial-fixes' });
  writeApply(dir, planApply(dir, { hosts: ['claude-code', 'codex'], skills: false }));
  const reviewer = read(dir, '.claude/agents/reviewer.md');
  assert.doesNotMatch(reviewer, /^tools:/m);
  assert.match(reviewer, /You may fix typos and formatting/);
  assert.match(read(dir, '.codex/agents/reviewer.toml'), /workspace-write/);
  rmSync(dir, { recursive: true, force: true });
});

test('reconfiguring the roster prunes the agent files of roles that are gone', () => {
  const dir = project();
  writeApply(dir, planApply(dir, { hosts: ['claude-code'], skills: false }));
  assert.ok(existsSync(path.join(dir, '.claude/agents/planner.md')));
  writeFileSync(path.join(dir, '.claude/agents/mine.md'), '---\nname: mine\n---\nHand-written.\n');
  const answers = { ...recommended, roster: 'implementer-reviewer' };
  applyReconfigure({ project: dir, result: planReconfigure({ project: dir, pack, answers, ...base }) });
  const plan = planApply(dir, { hosts: ['claude-code'], skills: false });
  assert.deepEqual(plan.stale, ['.claude/agents/explorer.md', '.claude/agents/planner.md', '.claude/agents/tester.md']);
  assert.ok(diffApply(dir, plan).includes('stale: .claude/agents/planner.md'));
  writeApply(dir, plan);
  assert.deepEqual(readdirSync(path.join(dir, '.claude/agents')).sort(), ['implementer.md', 'mine.md', 'reviewer.md']);
  rmSync(dir, { recursive: true, force: true });
});

test('the in-repo worktree location is guarded by a gitignore check', async () => {
  const dir = project({ ...recommended, 'worktree-location': 'in-repo-dir' });
  const check = async () => (await runTier3(dir, { onlyGuardrail: 'worktree-dir-is-gitignored' }))[0];
  assert.equal((await check()).ok, false);
  writeFileSync(path.join(dir, '.gitignore'), '.worktrees/\n');
  assert.equal((await check()).ok, true);
  rmSync(dir, { recursive: true, force: true });
});

// ---- worktree command ----

function repo(answers = recommended) {
  const parent = realpathSync(mkdtempSync(path.join(tmpdir(), 'gg-wt-')));
  const dir = path.join(parent, 'app');
  mkdirSync(dir);
  const git = (...a) => execFileSync('git', a, { cwd: dir, stdio: 'ignore' });
  git('init', '-q', '-b', 'main');
  git('config', 'user.email', 't@example.com');
  git('config', 'user.name', 't');
  git('config', 'commit.gpgsign', 'false');
  mkdirSync(path.join(dir, 'docs/skills'), { recursive: true });
  writeFileSync(path.join(dir, 'docs/skills/tags.md'), 'practice-packs — x\nagent-roles — x\nharness — x\nguardrail — x\n');
  if (answers) applyRender({ root: dir, plan: planRender({ root: dir, pack, answers, ...base }) });
  writeFileSync(path.join(dir, 'a.txt'), 'a\n');
  git('add', '-A');
  git('commit', '-q', '-m', 'init');
  return { parent, dir, git };
}

test('worktree new creates a sibling worktree on a new branch and list shows it', () => {
  const { parent, dir } = repo();
  const made = newWorktree(dir, 'login');
  assert.equal(made.path, path.join(parent, 'app-wt', 'login'));
  assert.equal(made.branch, 'feat/login');
  assert.ok(existsSync(path.join(made.path, 'a.txt')));
  assert.deepEqual(listWorktrees(dir).map((t) => [path.basename(t.path), t.branch, t.main]), [['app', 'main', true], ['login', 'feat/login', false]]);
  const out = spawnSync('node', [cli, 'worktree', 'list', '--json'], { cwd: made.path, encoding: 'utf8' });
  assert.equal(JSON.parse(out.stdout).length, 2);
  assert.throws(() => newWorktree(dir, 'login'), /already exists|already/);
  assert.throws(() => newWorktree(dir, 'Bad Slug'), /slug/);
  rmSync(parent, { recursive: true, force: true });
});

test('worktree new refuses beyond the concurrency limit and when the project does not use worktrees', () => {
  const { parent, dir } = repo({ ...recommended, 'max-concurrent': '2' });
  newWorktree(dir, 'one');
  newWorktree(dir, 'two');
  assert.throws(() => newWorktree(dir, 'three'), /limit is 2/);
  const none = repo({ ...recommended, isolation: 'no-isolation', 'worktree-location': undefined });
  assert.throws(() => newWorktree(none.dir, 'x'), /does not use worktrees/);
  const host = repo({ ...recommended, 'worktree-location': 'host-default' });
  assert.throws(() => newWorktree(host.dir, 'x'), /host default/);
  for (const p of [parent, none.parent, host.parent]) rmSync(p, { recursive: true, force: true });
});

test('worktree new honors the in-repo location and defaults to the recommended answers when unadopted', () => {
  const inRepo = repo({ ...recommended, 'worktree-location': 'in-repo-dir' });
  assert.equal(newWorktree(inRepo.dir, 'x').path, path.join(inRepo.dir, '.worktrees', 'x'));
  const bare = repo(null);
  assert.equal(newWorktree(bare.dir, 'y').path, path.join(bare.parent, 'app-wt', 'y'));
  for (const p of [inRepo.parent, bare.parent]) rmSync(p, { recursive: true, force: true });
});

test('worktree clean removes merged worktrees only and keeps new, dirty and unmerged ones', () => {
  const { parent, dir, git } = repo({ ...recommended, 'max-concurrent': '4' });
  const merged = newWorktree(dir, 'merged');
  const fresh = newWorktree(dir, 'fresh');
  const dirty = newWorktree(dir, 'dirty');
  const unmerged = newWorktree(dir, 'unmerged');
  const commit = (wt, file) => {
    writeFileSync(path.join(wt.path, file), `${file}\n`);
    execFileSync('git', ['add', '-A'], { cwd: wt.path });
    execFileSync('git', ['commit', '-q', '-m', file], { cwd: wt.path });
  };
  commit(merged, 'm.txt');
  commit(dirty, 'd.txt');
  commit(unmerged, 'u.txt');
  git('merge', '--no-ff', '-q', '-m', 'merge', merged.branch);
  git('merge', '--no-ff', '-q', '-m', 'merge', dirty.branch);
  writeFileSync(path.join(dirty.path, 'wip.txt'), 'wip\n');

  const verdict = Object.fromEntries(planClean(dir).map((t) => [path.basename(t.path), t.action]));
  assert.deepEqual(verdict, { merged: 'remove', fresh: 'keep', dirty: 'keep', unmerged: 'keep' });

  const dry = cleanWorktrees(dir, { dryRun: true });
  assert.equal(dry.filter((t) => t.action === 'remove').length, 1);
  assert.ok(existsSync(merged.path));

  cleanWorktrees(dir);
  assert.ok(!existsSync(merged.path));
  for (const wt of [fresh, dirty, unmerged]) assert.ok(existsSync(wt.path), wt.branch);
  assert.equal(execFileSync('git', ['branch', '--list', merged.branch], { cwd: dir, encoding: 'utf8' }).trim(), '');
  rmSync(parent, { recursive: true, force: true });
});

test('worktree clean also removes worktrees whose remote branch was deleted, keeping the unmerged branch', () => {
  const { parent, dir, git } = repo();
  const remote = path.join(parent, 'remote.git');
  execFileSync('git', ['init', '-q', '--bare', remote]);
  git('remote', 'add', 'origin', remote);
  git('push', '-q', 'origin', 'main');
  const squashed = newWorktree(dir, 'squashed');
  writeFileSync(path.join(squashed.path, 's.txt'), 's\n');
  execFileSync('git', ['add', '-A'], { cwd: squashed.path });
  execFileSync('git', ['commit', '-q', '-m', 's'], { cwd: squashed.path });
  execFileSync('git', ['push', '-q', '-u', 'origin', squashed.branch], { cwd: squashed.path, stdio: 'ignore' });
  git('push', '-q', 'origin', '--delete', squashed.branch);
  git('fetch', '-q', '--prune', 'origin');
  const [t] = planClean(dir);
  assert.deepEqual([t.action, t.reason], ['remove', 'remote branch deleted']);
  const [done] = cleanWorktrees(dir);
  assert.equal(done.branchDeleted, false);
  assert.ok(!existsSync(squashed.path));
  assert.match(execFileSync('git', ['branch', '--list', squashed.branch], { cwd: dir, encoding: 'utf8' }), /feat\/squashed/);
  rmSync(parent, { recursive: true, force: true });
});
