import { test } from 'node:test';
import assert from 'node:assert/strict';
import { mkdtempSync, mkdirSync, writeFileSync, appendFileSync, rmSync } from 'node:fs';
import { tmpdir } from 'node:os';
import path from 'node:path';
import { fileURLToPath } from 'node:url';
import { execFileSync, spawnSync } from 'node:child_process';
import { suggestRefs } from '../src/refs.mjs';
import { cleanGitEnv } from '../src/git-env.mjs';

const cli = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..', 'bin', 'go-getter.mjs');
const env = cleanGitEnv(process.env);
const git = (cwd, ...args) => execFileSync('git', args, { cwd, env, encoding: 'utf8', stdio: ['ignore', 'pipe', 'pipe'] });
const today = '2026-10-05';

const artifact = (id, fields, body = 'x\n') => `---\nid: ${id}\ntitle: Title of ${id}\nstatus: active\ndate: 2026-10-01\n${fields}---\n\n${body}`;
const FILES = {
  'docs/skills/tags.md': '---\nid: tags\ntitle: Tags\nstatus: active\ndate: 2026-10-01\ntags: [shared]\n---\n\nalpha — a\nbeta — b\ndelta — d\nepsilon — e\nshared — s (umbrella)\n',
  'docs/decisions/0001-base.md': artifact('0001-base', 'tags: [alpha, shared]\ngo-getter:\n  generated-by: roster@0.1.0\n'),
  'docs/decisions/0002-roster.md': artifact('0002-roster', 'tags: [beta]\ngo-getter:\n  generated-by: roster@0.1.0\n'),
  'docs/decisions/0003-other.md': artifact('0003-other', 'tags: [alpha]\n'),
  'docs/decisions/0004-code.md': artifact('0004-code', 'tags: [epsilon]\n'),
  'docs/decisions/0005-old.md': artifact('0005-old', 'tags: [epsilon]\n'),
  'docs/guardrails/size-cap.md': artifact(
    'size-cap',
    'tags: [delta, shared]\ngoverned-by: 0004-code\ngrounded-in: [0004-code]\ngo-getter:\n  enforcement:\n    - tier: 3\n      check: cap\n      run: builtin:file-max-lines path=src/app.mjs max=10\n',
  ),
  'docs/guardrails/other-rule.md': artifact('other-rule', 'tags: [delta]\n'),
  'docs/guardrails/third-rule.md': artifact('third-rule', 'tags: [epsilon]\n'),
  'docs/guardrails/fourth-rule.md': artifact('fourth-rule', 'tags: [epsilon]\n'),
  'docs/facts/0001-api.md': artifact('0001-api', 'tags: [beta]\ngoverned-by: 0001-base\nexpires: 2026-10-20\n'),
  'docs/facts/0002-later.md': artifact('0002-later', 'tags: [alpha]\ngoverned-by: 0001-base\nexpires: 2027-06-01\n'),
  'agents/bot.md': '<!-- Generated by go-getter apply from 0002-roster; do not edit. -->\nbot\n',
  'src/app.mjs': 'export {};\n',
  'docs/plans/p.md': '# Plan\n\n### 1.1 Do the thing — [ ]\nDo: it.\n',
};

function fixture() {
  const dir = mkdtempSync(path.join(tmpdir(), 'gg-refs-'));
  for (const [rel, content] of Object.entries(FILES)) {
    mkdirSync(path.dirname(path.join(dir, rel)), { recursive: true });
    writeFileSync(path.join(dir, rel), content);
  }
  git(dir, 'init', '-q', '-b', 'main');
  git(dir, 'add', '-A');
  git(dir, '-c', 'user.name=t', '-c', 'user.email=t@example.com', 'commit', '-q', '-m', 'init');
  return dir;
}

const rows = (refs) => ({ must: refs.must.map((r) => `${r.path} — ${r.reason}`), nice: refs.nice.map((r) => `${r.path} — ${r.reason}`) });

test('an artifact edit that completes a plan step', () => {
  const dir = fixture();
  try {
    appendFileSync(path.join(dir, 'docs/decisions/0001-base.md'), 'more\n');
    writeFileSync(path.join(dir, 'docs/plans/p.md'), FILES['docs/plans/p.md'].replace('[ ]', '[x]'));
    git(dir, 'add', '-A');
    assert.deepEqual(rows(suggestRefs(dir, { staged: true, today })), {
      must: ['docs/decisions/0001-base.md — changed in this diff', 'docs/plans/p.md — completes step 1.1'],
      nice: ['docs/facts/0001-api.md — expires 2026-10-20; re-check before relying on it', 'docs/decisions/0003-other.md — shares tag alpha with 0001-base'],
    });
  } finally {
    rmSync(dir, { recursive: true, force: true });
  }
});

test('a generated-file edit names the decisions of the pack it is generated from', () => {
  const dir = fixture();
  try {
    appendFileSync(path.join(dir, 'agents/bot.md'), 'edit\n');
    git(dir, 'add', '-A');
    assert.deepEqual(rows(suggestRefs(dir, { staged: true, today })), {
      must: ['docs/decisions/0001-base.md — agents/bot.md is generated from it (roster pack)', 'docs/decisions/0002-roster.md — agents/bot.md is generated from it (roster pack)'],
      nice: ['docs/facts/0001-api.md — expires 2026-10-20; re-check before relying on it', 'docs/decisions/0003-other.md — shares tag alpha with 0001-base'],
    });
  } finally {
    rmSync(dir, { recursive: true, force: true });
  }
});

test('a code file named by a guardrail check', () => {
  const dir = fixture();
  try {
    appendFileSync(path.join(dir, 'src/app.mjs'), '// edit\n');
    git(dir, 'add', '-A');
    assert.deepEqual(rows(suggestRefs(dir, { staged: true, today })), {
      must: ['docs/guardrails/size-cap.md — its check covers src/app.mjs'],
      nice: ['docs/decisions/0004-code.md — governs size-cap', 'docs/guardrails/other-rule.md — shares tag delta with size-cap'],
    });
  } finally {
    rmSync(dir, { recursive: true, force: true });
  }
});

test('an added decision brings the decision it supersedes; the CLI prints JSON for a base ref', () => {
  const dir = fixture();
  try {
    git(dir, 'checkout', '-q', '-b', 'feat/x');
    writeFileSync(path.join(dir, 'docs/decisions/0006-new.md'), artifact('0006-new', 'tags: [beta]\n', 'Supersedes 0005.\n'));
    git(dir, 'add', '-A');
    git(dir, '-c', 'user.name=t', '-c', 'user.email=t@example.com', 'commit', '-q', '-m', 'new');
    const out = spawnSync(process.execPath, [cli, 'refs', '--base', 'main', '--json'], { cwd: dir, env, encoding: 'utf8' });
    assert.equal(out.status, 0, out.stderr);
    const refs = JSON.parse(out.stdout);
    assert.deepEqual(
      refs.must.map((r) => [r.path, r.reason]),
      [
        ['docs/decisions/0006-new.md', 'added in this diff'],
        ['docs/decisions/0005-old.md', 'superseded by 0006-new'],
      ],
    );
    assert.ok(refs.nice.every((r) => !r.reason.includes('Title of')));
  } finally {
    rmSync(dir, { recursive: true, force: true });
  }
});
