import { test } from 'node:test';
import assert from 'node:assert/strict';
import { mkdtempSync, mkdirSync, writeFileSync, readFileSync, appendFileSync, rmSync } from 'node:fs';
import { tmpdir } from 'node:os';
import path from 'node:path';
import { fileURLToPath } from 'node:url';
import { spawnSync } from 'node:child_process';
import { buildRunbook, checkRunbook, runbookPath } from '../src/runbook.mjs';

const cli = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..', 'bin', 'go-getter.mjs');

const art = (id, title, fields, body) => `---\nid: ${id}\ntitle: ${title}\nstatus: active\ndate: 2026-10-10\ntags: [guardrail]\n${fields}---\n\n${body}\n`;
const FILES = {
  'docs/guardrails/keep-it-small.md': art('keep-it-small', 'Keep changes small', 'governed-by: 0001-small\ngrounded-in: [0001-small, 0002-review-time]\nderivation-note: x\n', '## Guardrail\n\nA change stays under the review limit.'),
  'docs/guardrails/no-steps.md': art('no-steps', 'No steps', 'governed-by: 0001-small\ngrounded-in: [0001-small]\nderivation-note: x\n', '## Guardrail\n\nNothing operationalizes this.'),
  'docs/guardrails/bad-ref.md': art('bad-ref', 'Bad ref', 'governed-by: 0001-small\ngrounded-in: [0099-missing]\nderivation-note: x\n', '## Guardrail\n\nx'),
  'docs/skills/splitting-a-change.md': art('splitting-a-change', 'Split a change', 'operationalizes: [keep-it-small, bad-ref, no-steps-other]\n', '## Procedure\n\n1. Count the lines.\n2. Split above the limit.'),
  'docs/facts/0002-review-time.md': art('0002-review-time', 'Review time grows with size', 'kind: environmental\ngoverned-by: 0001-small\n', 'Review time doubles above 400 lines.'),
  'docs/guardrails/other-rule.md': art('other-rule', 'Other rule', 'governed-by: 0001-small\ngrounded-in: [0001-small]\nderivation-note: x\n', '## Guardrail\n\nThe other norm.'),
  'docs/guardrails/third-rule.md': art('third-rule', 'Third rule', 'governed-by: 0001-small\ngrounded-in: [0001-small]\nderivation-note: x\n', '## Guardrail\n\nThe third norm.'),
  'docs/facts/0003-limits.md': art('0003-limits', 'Review limits', 'kind: environmental\ngoverned-by: 0001-small\n', 'Intro line.\n\n## Lines\n\nLimit is 400 lines.\n\n### Why\n\nReviewers tire.\n\n## Files\n\nLimit is 20 files.'),
  'docs/skills/shared-steps.md': art('shared-steps', 'Shared steps', 'operationalizes: [other-rule, third-rule]\n', '## Procedure\n\n1. Do the shared thing.'),
  'docs/skills/plain-sop.md': art('plain-sop', 'Plain SOP', '', '## Procedure\n\n1. Restart the service.\n2. Check the log.'),
  'docs/skills/sop-with-uses.md': art('sop-with-uses', 'SOP with uses', 'uses:\n  - 0003-limits#Lines\n  - 0002-review-time\noperationalizes: [other-rule]\n', '## Procedure\n\n1. Count against the limits.'),
  'docs/skills/sop-bad-id.md': art('sop-bad-id', 'SOP bad id', 'uses:\n  - 0042-nothing\n', '## Procedure\n\n1. x'),
  'docs/skills/sop-bad-heading.md': art('sop-bad-heading', 'SOP bad heading', 'uses:\n  - 0003-limits#Missing\n', '## Procedure\n\n1. x'),
  'docs/skills/sop-bad-norm.md': art('sop-bad-norm', 'SOP bad norm', 'operationalizes: [0001-small]\n', '## Procedure\n\n1. x'),
  'docs/decisions/0001-small.md': art('0001-small', 'Changes are small', 'track: process\n', '## Decision\n\nKeep them small.'),
};

function kb() {
  const dir = mkdtempSync(path.join(tmpdir(), 'gg-runbook-'));
  for (const [rel, content] of Object.entries(FILES)) {
    mkdirSync(path.dirname(path.join(dir, rel)), { recursive: true });
    writeFileSync(path.join(dir, rel), content);
  }
  return dir;
}
const cleanup = (dir) => rmSync(dir, { recursive: true, force: true });
const run = (dir, ...args) => spawnSync(process.execPath, [cli, 'runbook', ...args], { cwd: dir, encoding: 'utf8' });

test('a runbook holds the norm, the steps and the grounded fact; a grounding decision is named, not inlined', () => {
  const dir = kb();
  try {
    const text = buildRunbook(dir, 'keep-it-small');
    assert.match(text, /^---\nname: keep-it-small\ndescription: Use when the task involves: Keep changes small\.\n---/);
    assert.match(text, /## Norm\n\nA change stays under the review limit\./);
    assert.match(text, /## Steps\n\n1\. Count the lines\.\n2\. Split above the limit\./);
    assert.match(text, /### Review time grows with size\n\nReview time doubles above 400 lines\./);
    assert.match(text, /## Grounded in\n\n- 0001-small\n/);
    assert.doesNotMatch(text, /Keep them small/);
    assert.match(text, /Generated by go-getter runbook from keep-it-small, splitting-a-change, 0002-review-time; do not edit\./);
  } finally {
    cleanup(dir);
  }
});

test('the check passes on a fresh build and fails after the procedure or a fact changes', () => {
  const dir = kb();
  try {
    assert.equal(run(dir, 'build', 'keep-it-small').status, 0);
    assert.equal(checkRunbook(dir, 'keep-it-small').ok, true);
    assert.equal(run(dir, 'build', 'keep-it-small', '--check').status, 0);
    appendFileSync(path.join(dir, 'docs/skills/splitting-a-change.md'), '3. Open one pull request each.\n');
    assert.equal(checkRunbook(dir, 'keep-it-small').ok, false);
    assert.equal(run(dir, 'build', 'keep-it-small', '--check').status, 1);
    run(dir, 'build', 'keep-it-small');
    appendFileSync(path.join(dir, 'docs/facts/0002-review-time.md'), 'More.\n');
    assert.equal(checkRunbook(dir, 'keep-it-small').ok, false);
  } finally {
    cleanup(dir);
  }
});

test('a missing runbook fails the check and names the command', () => {
  const dir = kb();
  try {
    const r = checkRunbook(dir, 'keep-it-small');
    assert.equal(r.ok, false);
    assert.match(r.message, new RegExp(`${runbookPath('keep-it-small')} does not exist`));
  } finally {
    cleanup(dir);
  }
});

test('a guardrail without a procedure, an unknown guardrail and a dangling grounding fail with the id', () => {
  const dir = kb();
  try {
    assert.throws(() => buildRunbook(dir, 'no-steps'), /"no-steps" has no procedure/);
    assert.throws(() => buildRunbook(dir, 'nothing'), /no guardrail or procedure "nothing"/);
    assert.throws(() => buildRunbook(dir, 'bad-ref'), /grounded in "0099-missing"/);
    const r = run(dir, 'build', 'no-steps');
    assert.equal(r.status, 1);
    assert.match(r.stderr, /no-steps/);
  } finally {
    cleanup(dir);
  }
});

test('the command rejects bad usage', () => {
  const dir = kb();
  try {
    assert.equal(run(dir).status, 2);
    assert.equal(run(dir, 'build').status, 2);
    assert.equal(run(dir, 'build', 'keep-it-small', '--force').status, 2);
  } finally {
    cleanup(dir);
  }
});

test('check runbooks passes with none, with fresh ones, and fails on a stale or orphaned runbook', () => {
  const dir = kb();
  const check = () => spawnSync(process.execPath, [cli, 'check', 'runbooks', '--project', dir], { encoding: 'utf8' });
  try {
    assert.equal(check().status, 0);
    assert.match(check().stdout, /ok \(0 runbooks\)/);
    run(dir, 'build', 'keep-it-small');
    assert.match(check().stdout, /ok \(1 runbooks\)/);
    appendFileSync(path.join(dir, 'docs/skills/splitting-a-change.md'), '3. More.\n');
    const stale = check();
    assert.equal(stale.status, 1);
    assert.match(stale.stderr, /keep-it-small\/SKILL\.md is out of date/);
    mkdirSync(path.join(dir, 'docs/runbooks/gone'), { recursive: true });
    writeFileSync(path.join(dir, 'docs/runbooks/gone/SKILL.md'), 'x\n');
    assert.match(check().stderr, /no guardrail or procedure "gone"/);
  } finally {
    cleanup(dir);
  }
});

test('a procedure runbook inlines a used artifact whole, or one section only, then the norms it operationalizes', () => {
  const dir = kb();
  try {
    const text = buildRunbook(dir, 'sop-with-uses');
    assert.match(text, /^---\nname: sop-with-uses\n/);
    assert.match(text, /## Steps\n\n1\. Count against the limits\./);
    assert.match(text, /### Review limits: Lines\n\nLimit is 400 lines\.\n\n### Why\n\nReviewers tire\./);
    assert.doesNotMatch(text, /Limit is 20 files|Intro line/);
    assert.match(text, /### Review time grows with size\n\nReview time doubles above 400 lines\./);
    assert.match(text, /## Norms\n\n### Other rule\n\nThe other norm\./);
    assert.match(text, /Generated by go-getter runbook from sop-with-uses, 0003-limits, 0002-review-time, other-rule; do not edit\./);
    assert.ok(text.indexOf('## Steps') < text.indexOf('## Uses') && text.indexOf('## Uses') < text.indexOf('## Norms'));
  } finally {
    cleanup(dir);
  }
});

test('a procedure serving several guardrails builds once; one with neither field builds its steps alone', () => {
  const dir = kb();
  try {
    const shared = buildRunbook(dir, 'shared-steps');
    assert.equal(shared.split('1. Do the shared thing.').length, 2);
    assert.match(shared, /### Other rule[\s\S]*### Third rule/);
    const plain = buildRunbook(dir, 'plain-sop');
    assert.match(plain, /## Steps\n\n1\. Restart the service\.\n2\. Check the log\.\n$/);
    assert.doesNotMatch(plain, /## Uses|## Norms/);
  } finally {
    cleanup(dir);
  }
});

test('a dangling use, a missing heading and a norm that is not a guardrail fail naming the id', () => {
  const dir = kb();
  try {
    assert.throws(() => buildRunbook(dir, 'sop-bad-id'), /"sop-bad-id" uses "0042-nothing", which does not exist/);
    assert.throws(() => buildRunbook(dir, 'sop-bad-heading'), /0003-limits has no heading "Missing"/);
    assert.throws(() => buildRunbook(dir, 'sop-bad-norm'), /operationalizes "0001-small", which is not a guardrail/);
  } finally {
    cleanup(dir);
  }
});

test('the procedure runbook drifts when a used fact changes, but not when an unused section does', () => {
  const dir = kb();
  try {
    assert.equal(run(dir, 'build', 'sop-with-uses').status, 0);
    assert.equal(checkRunbook(dir, 'sop-with-uses').ok, true);
    appendFileSync(path.join(dir, 'docs/facts/0003-limits.md'), '\nExtra files note.\n');
    assert.equal(checkRunbook(dir, 'sop-with-uses').ok, true, 'the Files section is not used');
    writeFileSync(path.join(dir, 'docs/facts/0003-limits.md'), readFileSync(path.join(dir, 'docs/facts/0003-limits.md'), 'utf8').replace('Limit is 400 lines.', 'Limit is 300 lines.'));
    assert.equal(checkRunbook(dir, 'sop-with-uses').ok, false);
    assert.equal(run(dir, 'build', 'sop-with-uses', '--check').status, 1);
  } finally {
    cleanup(dir);
  }
});
