import { test } from 'node:test';
import assert from 'node:assert/strict';
import { mkdtempSync, mkdirSync, writeFileSync, readFileSync, appendFileSync, rmSync } from 'node:fs';
import { tmpdir } from 'node:os';
import path from 'node:path';
import { fileURLToPath } from 'node:url';
import { spawnSync } from 'node:child_process';
import { buildRunbook, checkRunbook, runbookPath } from '../src/runbook.mjs';

const cli = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..', 'bin', 'go-getter.mjs');

const art = (id, title, fields, body) => `---\nid: ${id}\ntitle: ${title}\nstatus: active\ndate: 2026-10-10\ntags: [guardrail]\n${fields}---\n\n${body}\n`;
const FILES = {
  'docs/guardrails/keep-it-small.md': art('keep-it-small', 'Keep changes small', 'governed-by: 0001-small\ngrounded-in: [0001-small, 0002-review-time]\nderivation-note: x\n', '## Guardrail\n\nA change stays under the review limit.'),
  'docs/guardrails/no-steps.md': art('no-steps', 'No steps', 'governed-by: 0001-small\ngrounded-in: [0001-small]\nderivation-note: x\n', '## Guardrail\n\nNothing operationalizes this.'),
  'docs/guardrails/bad-ref.md': art('bad-ref', 'Bad ref', 'governed-by: 0001-small\ngrounded-in: [0099-missing]\nderivation-note: x\n', '## Guardrail\n\nx'),
  'docs/skills/splitting-a-change.md': art('splitting-a-change', 'Split a change', 'operationalizes: [keep-it-small, bad-ref, no-steps-other]\n', '## Procedure\n\n1. Count the lines.\n2. Split above the limit.'),
  'docs/facts/0002-review-time.md': art('0002-review-time', 'Review time grows with size', 'kind: environmental\ngoverned-by: 0001-small\n', 'Review time doubles above 400 lines.'),
  'docs/decisions/0001-small.md': art('0001-small', 'Changes are small', 'track: process\n', '## Decision\n\nKeep them small.'),
};

function kb() {
  const dir = mkdtempSync(path.join(tmpdir(), 'gg-runbook-'));
  for (const [rel, content] of Object.entries(FILES)) {
    mkdirSync(path.dirname(path.join(dir, rel)), { recursive: true });
    writeFileSync(path.join(dir, rel), content);
  }
  return dir;
}
const cleanup = (dir) => rmSync(dir, { recursive: true, force: true });
const run = (dir, ...args) => spawnSync(process.execPath, [cli, 'runbook', ...args], { cwd: dir, encoding: 'utf8' });

test('a runbook holds the norm, the steps and the grounded fact; a grounding decision is named, not inlined', () => {
  const dir = kb();
  try {
    const text = buildRunbook(dir, 'keep-it-small');
    assert.match(text, /^---\nname: keep-it-small\ndescription: Use when the task involves: Keep changes small\.\n---/);
    assert.match(text, /## Norm\n\nA change stays under the review limit\./);
    assert.match(text, /## Steps\n\n1\. Count the lines\.\n2\. Split above the limit\./);
    assert.match(text, /### Review time grows with size\n\nReview time doubles above 400 lines\./);
    assert.match(text, /## Grounded in\n\n- 0001-small\n/);
    assert.doesNotMatch(text, /Keep them small/);
    assert.match(text, /Generated by go-getter runbook from keep-it-small, splitting-a-change, 0002-review-time; do not edit\./);
  } finally {
    cleanup(dir);
  }
});

test('the check passes on a fresh build and fails after the procedure or a fact changes', () => {
  const dir = kb();
  try {
    assert.equal(run(dir, 'build', 'keep-it-small').status, 0);
    assert.equal(checkRunbook(dir, 'keep-it-small').ok, true);
    assert.equal(run(dir, 'build', 'keep-it-small', '--check').status, 0);
    appendFileSync(path.join(dir, 'docs/skills/splitting-a-change.md'), '3. Open one pull request each.\n');
    assert.equal(checkRunbook(dir, 'keep-it-small').ok, false);
    assert.equal(run(dir, 'build', 'keep-it-small', '--check').status, 1);
    run(dir, 'build', 'keep-it-small');
    appendFileSync(path.join(dir, 'docs/facts/0002-review-time.md'), 'More.\n');
    assert.equal(checkRunbook(dir, 'keep-it-small').ok, false);
  } finally {
    cleanup(dir);
  }
});

test('a missing runbook fails the check and names the command', () => {
  const dir = kb();
  try {
    const r = checkRunbook(dir, 'keep-it-small');
    assert.equal(r.ok, false);
    assert.match(r.message, new RegExp(`${runbookPath('keep-it-small')} does not exist`));
  } finally {
    cleanup(dir);
  }
});

test('a guardrail without a procedure, an unknown guardrail and a dangling grounding fail with the id', () => {
  const dir = kb();
  try {
    assert.throws(() => buildRunbook(dir, 'no-steps'), /"no-steps" has no procedure/);
    assert.throws(() => buildRunbook(dir, 'nothing'), /no guardrail "nothing"/);
    assert.throws(() => buildRunbook(dir, 'bad-ref'), /grounded in "0099-missing"/);
    const r = run(dir, 'build', 'no-steps');
    assert.equal(r.status, 1);
    assert.match(r.stderr, /no-steps/);
  } finally {
    cleanup(dir);
  }
});

test('the command rejects bad usage', () => {
  const dir = kb();
  try {
    assert.equal(run(dir).status, 2);
    assert.equal(run(dir, 'build').status, 2);
    assert.equal(run(dir, 'build', 'keep-it-small', '--force').status, 2);
  } finally {
    cleanup(dir);
  }
});

test('check runbooks passes with none, with fresh ones, and fails on a stale or orphaned runbook', () => {
  const dir = kb();
  const check = () => spawnSync(process.execPath, [cli, 'check', 'runbooks', '--project', dir], { encoding: 'utf8' });
  try {
    assert.equal(check().status, 0);
    assert.match(check().stdout, /ok \(0 runbooks\)/);
    run(dir, 'build', 'keep-it-small');
    assert.match(check().stdout, /ok \(1 runbooks\)/);
    appendFileSync(path.join(dir, 'docs/skills/splitting-a-change.md'), '3. More.\n');
    const stale = check();
    assert.equal(stale.status, 1);
    assert.match(stale.stderr, /keep-it-small\/SKILL\.md is out of date/);
    mkdirSync(path.join(dir, 'docs/runbooks/gone'), { recursive: true });
    writeFileSync(path.join(dir, 'docs/runbooks/gone/SKILL.md'), 'x\n');
    assert.match(check().stderr, /no guardrail "gone"/);
  } finally {
    cleanup(dir);
  }
});
